import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class HindiService {

  constructor() { }

  langs: any = {
    "All": "सभी",
    "Market": "मार्केट",
    "Announce": "अनाउंस",
    "Profile": "प्रोफाइल",
    "Profiles": "प्रोफाइल",
    "Home": "होम",
    "Chat": "चैट",
    "Spaarks": "स्पार्क्स",
    "New spaark": "नई स्पार्क",
    "Explore": "खोजें",
    "just now": "अभी",
    "comments": "कमैंट्स",
    "views": "ने देखा",
    "mins ago": "मिनट पहले",
    "within ": "में",
    "mts": "mts",
    "Show more": "और देखें",
    "show less": "कम देखें",
    "View Market Profile": "मार्केट प्रोफाइल देखें",
    "View": "देखें",
    //   "Market Profile":"मार्केट प्रोफाइल",
    "hours ago": "घंटे पहले",
    "hours": "घंटे",
    "report": "रिपोर्ट",
    "Report": "रिपोर्ट",
    "Block": "ब्लॉक",
    "block": "ब्लॉक",
    "Looking for something": "खोजें",
    "Get Started": "शुरू करें ",
    "GET STARTED": "शुरू करें ",
    "Recent chats": "चैट्स",
    "beyond": " के बाद में",
    "Collect Review": "कलेक्ट रिव्यु",
    "Did you complete your work with": "क्या आपका काम इनके साथ ख़त्म हुआ -",
    "Completed": "ख़त्म हुआ",
    "Not Yet": "अभी नहीं",
    "Ignore": "जाने दें ",
    "IGNORE": "जाने दें",
    "reviews": "रिव्यु",
    "My QR": "मेरा QR",
    "This QR code can be used for Web Login.": "यह QR कोड वेब लॉगिन के लिए इस्तेमाल होगा",
    "Notifications": "नोटिफिकेशन्स",

    "Images posted": "इमेजिज़ पोस्टेड",
    "Spaarks timeline": "स्पार्क्स टाइमलाइन ",
    "Timeline": "टाइमलाइन",
    "Delete": "डिलीट",
    "Seller": "सैलर",
    "Sellers": "सैलर",
    "Take Ratings & Reviews for your service here. ": "अपनी सर्विस के लिए रेटिंग & रिव्यु लें ",
    "Take": "अपनी सर्विस के लिए",
    "for your service here.": "लें",
    "Ratings & Reviews": "रेटिंग & रिव्यु",
    "Rating": "रेटिंग",
    "About service": "सर्विस के बारे में",
    "Show QR": "QR दिखाएं",
    "User can give you rating by scanning this QR code.": "यह QR कोड स्कैन कर यूजर रेटिंग दे सकता है। ",
    "About me": "मेरे बारे में ",
    "characters remaining": "अक्षर बचे",
    "Comment here": "यहाँ कमैंट करें ",
    "Replies": "रिप्लाई",
    "Type here": "टाइप करें ",
    "More options": "और ऑप्शंस",
    "Other": "अन्य",
    "Clear chat": "क्लियर चैट",
    "Exit chat": "चैट छोड़ें ",
    "User will not be able to chat or see each others spaarks.": "यूजर अब चैट नहीं कर सकते और एक दुसरे के स्पार्क्स नहीं देख सकते। ",
    "copy": "कॉपी",
    "Copy": "कॉपी",
    "Forward": "फॉरवर्ड",
    "Clear": "क्लियर",
    "New friend request": "नई फ्रैंड रिक्वेस्ट",
    "Delete for me": "मेरे लिए डिलीट करें",
    "Update photo": "फोटो अपडेट",
    "Remove photo": "फोटो हटाएं",
    "Delete for both": "दोनों के लिए डिलीट करें",
    "Type a message": "मैसेज टाइप करें ",
    "Choose an option": "एक विकल्प चुनें",
    "To start a chat go to any Spaark and click on Chat.": "चैट शुरू करने के लिए किसी स्पार्क पर जाएँ और चैट क्लिक करें। ",
    "Spaark": 'स्पार्क',
    "Select any to create Spaark.": "स्पार्क क्रिएट करने के लिए कुछ चुनें",
    "Ticket Created": "टिकट बनाया गया",
    "Choose a service that suits you best": "एक सर्विस चुनें ",

    "Did not find your category?": "अपनी कैटेगरी नहीं मिली?",
    "Skip this Step": "यह स्टैप स्किप करें। ",
    "Categories": "कैटेगरी",
    "has sent you a connection request.": "आपको एक कनेक्शन रिक्वेस्ट भेजा है।",

    "Did not find your field?": "अपनी फील्ड नहीं मिली?",
    "Skip this step": "यह स्टैप स्किप करें।",

    "Add images": "फोटो जोड़ें",


    "Add video": "वीडियो जोड़ें",

    "Write the details you want to post here.": "पोस्ट करने के लिए यहाँ लिखें। ",

    "Connection preferences": "कनैक्शन चुनें",

    "Internet call where number is not required": "यह इंटरनेट कॉल है. नंबर की ज़रूरत नहीं है.",

    "Spaarks call": "स्पार्क्स कॉल",


    "Spaarks chat": "स्पार्क्स चैट",
    "Have something to Sell": "मुझसे कुछ खरीदें",
    "Offer a Service": "एक सेवा प्रदान करें",

    "Previous": "पिछला",

    "Next": "आगे",
    "NEXT": "आगे",
    "No profile for Anonymous and Makefriends": "फ्रैंड्स और गुमनाम पोस्ट्स प्रोफाइल में नहीं आते ",
    "Show my spaark on map": "मुझे स्पार्क मैप पर दिखाएं",
    "Show profile pic": "प्रोफाइल पिक दिखाएं",
    "Show my name": "मेरा नाम दिखाएं",
    "To start a chat go to any spaark and click on chat.": "चैट शुरू करने के लिए फ्रेंड्स फीचर में किसी भी स्पार्क पर जाएँ और चैट का अनुरोध भेजें। गुमनाम चैट के लिए अनुरोध भेजते हुए अपने नाम को छुपाएं।",
    "Spaarks are sorted by distance from you": "स्पार्क्स दूरी से छांटें",
    "Spaarks are sorted by time of posting.": "स्पार्क्स समय से छांटें",
    "Spaark remains at this location, even if you open the app at a new location": "स्पार्क इसी लोकेशन पर रहेगा.",
    "Pin spaark at this location": "इस लोकेशन पर स्पार्क पिन करें",
    "Distance": "दूरी",
    "Time": "समय",
    "Move spaark wherever I go": "स्पार्क मेरी लोकेशन के साथ चले",
    "Sort Spaarks by": "स्पार्क्स को छांटें करें",
    "Are you sure, you want to discard this Spaark?": "क्या आप वाकई इस स्पार्क को छोड़ना चाहते हैं?",
    "Are you sure, you want to delete this spaark?": "क्या आप वाकई इस स्पार्क को छोड़ना चाहते हैं?",
    "Are you sure, you want to report this Spaark?": "क्या आप वाकई इस स्पार्क को डिलीट करना चाहते हैं?",
    "I have a skill.": "मैं कुछ काम जानता हूँ",
    "I am looking for any type of work.": "कोई भी काम चलेगा",
    "Finish": "ख़त्म",
    "Cow/Buffalo": "गाय/भैंस",
    "Dairy": "डेरी",
    "Farm Machines": "कृषि मशीन",
    "Poultry/Goat": "पोल्ट्री/बकरी",
    "Pulses/Grains": "दाल/अनाज",
    "Seeds/Pesticides": "बीज/कीटनाशक",
    "Show directions": "डायरेक्शन",
    "Your interests are saved successfully.": "आपके इंटरेस्ट सेव हुए",
    "Show on googlemaps": "googlemaps पर दिखाएं",
    "Update interests": "इंटरेस्ट अपडेट करें",


    "FAQs": "FAQs",

    "Help": "हैल्प",

    "Business Queries": "बिज़नेस प्रश्न",


    "Connect With us": "हमसे जुड़ें",

    "Connect with us": "हमसे जुड़ें",
    "Connect With Us": "हमसे जुड़ें",

    "Terms & Policies": "टर्म्स पॉलिसीज़",


    "Settings": "सेटिंग्स",

    "Choose your interests": "अपने इंटरेस्ट चुनें ",

    "Select as many": "कितने भी चुनें",


    "Continue": "आगे",

    "Previous tickets": "पिछली टिकेट्स",

    "Contact us": "कॉन्टैक्ट करें",

    "Submit": "भेजें",
    "SUBMIT": "भेजें",

    "For any Promotions, Advertisements, Extended reach, etc.": "किसी विज्ञापन, पब्लिसिटी, और बिज़नेस के लिए.",
    "Please Contact us": "कृप्या कॉन्टैक्ट करें",

    "Previous conversations": "पिछले संवाद",


    "Spaarks Support": "स्पार्क्स टीम",

    "Terms & Conditions and Privacy Notice": "टर्म्स पॉलिसीज़",

    "Personal Details": "पर्सनल डिटेल",

    "Phone": "फ़ोन",

    "Change language": "भाषा बदलें (Change language)",


    "Blocked users": "ब्लॉक किए यूजर",

    "Logout": "लॉगआउट ",

    "Blocked on": "ब्लॉक किया ",

    "Unblock": "अनब्लॉक",
    "UNBLOCK": "अनब्लॉक",
    // "By clicking “OK” you are agreeing to accept our cookie policies.": "ओके करने से आप कुकी पॉलिसी स्वीकार कर रहे हैं.",

    "Hindi": "हिंदी",

    //"Spaarks connects you to your local area wherever you go":"जहाँ जाएँ स्पार्क्स से आस पास कनैक्ट करें",

    "Okay": "ओके",
    "OKAY": "ओके",
    "Location Access": "लोकेशन अनुमति",


    "Locate Me": "मुझे लोकेट करें",

    "or": "या",

    "Choose City": "शहर चुनें",

    "By logging in you agree to our Terms & Policies.": "लॉगिन करने से आप टर्म्स पॉलिसीज स्वीकार करते हैं",

    "Select City": "शहर चुनें",

    "Search Location": "लोकेशन ढूंढें",
    "Close": "बंद करे",
    "Popular Cities": "बड़े शहर",

    "Select Location": "लोकेशन चुनें",

    "Please drag the pin to your current precise location": "पिन को अपनी लोकेशन पर ले जाएँ",
    "Please drag the pin to your current location": "पिन को अपनी लोकेशन पर ले जाएँ",
    "Login to access this feature!": "इस फीचर के लिए लॉगिन करें ",
    "Share Spaark": "शेयर स्पार्क",
    "Login": "लॉगिन",

    "Login to Spaarks": "स्पार्क्स लॉगिन",
    "Login using QR": "QR से लॉगिन",
    "Or Login using Mobile number": "या मोबाइल नंबर से लॉगिन",
    "Login using mobile": "मोबाइल नंबर से लॉगिन",
    "By logging in, you agree to Spaarks Terms of Service, Cookie Policy, Privacy Policy and Content Policies.": "लॉगिन करने से आप टर्म्स पॉलिसीज स्वीकार करते हैं",
    "Login using Mobile number": "मोबाइल नंबर से लॉगिन",
    "You will recieve an OTP on your mobile number.": "इस नंबर पर OTP आएगा ",
    "You will recieve an": "इस नंबर पर",
    "on your mobile number.": "आएगा",
    "Enter your mobile number": "मोबाइल नंबर लिखें",
    "Enter your Mobile Number": "मोबाइल नंबर लिखें",

    "We never share your mobile number with anyone": "आपका नंबर कहीं शेयर नहीं होता है। ",
    "share": "शेयर",
    "Share": "शेयर",
    "Shares": "शेयर",
    "shares": "शेयर",
    "0 shares": "0 शेयर",
    "Request OTP": "रिक्वेस्ट OTP",
    "Enter": "एंटर",
    "OTP sent to": "OTP देखें +91-",
    "Resend OTP": "OTP फिर  भेजें",
    "Wrong mobile number?": "गलत मोबाइल नंबर",
    "Please login to post a comment": "कमैंट करने के लिए लॉगिन करें",
    "Connection permissons": "कनेक्शन की अनुमति",
    "Write something": "कुछ लिखो",
    "Write something about you.": "अपने बारे में लिखें",
    "Write about your service experience": "सर्विस के अनुभव के बारे में लिखें",
    "Enter your name": "अपना नाम लिखें",
    "Name cannot be empty": "नाम खली नहीं हो सकता ",
    "Enter alias name": "निकनेम",
    "Upload an Image or a Video": "फोटो या वीडियो अपलोड",
    "Format not supported": "यह फॉर्मैट सपोर्ट नहीं होता",
    "Image size cannot exceed 25MB": "फोटो 25mb से कम",
    "Video size cannot exceed 50MB": "वीडियो 50mb se कम",
    "Max 10 files can be uploaded": "अधिकतम 10 फाइल अपलोड",
    "File size cannot exceed 25MB": "फाइल 25mb से कम ",
    "Sorry, your browser does not support HTML5 geolocation.": "आपका ब्राउज़र HTML5 geolocation सपोर्ट नहीं करता.",
    "Please fill valid mobile number": "सही मोबाइल नंबर लिखें",
    "Please fill valid OTP": "सही OTP लिखें",
    "Please enter name less than 20 charecters": "20 अक्षर से कम में लिखें",
    "You are clicking too many times": "आप ज़्यादा बार क्लिक कर रहे हैं",
    "something went wrong": "कुछ गलत है",
    "only 5 files": "केवल 5 फाइल्स",
    "Upto 5 media files can be uploaded": "5 मीडिया फाइल तक अपलोड कर सकते हैं",

    "One video can be uploaded": "एक ही वीडियो अपलोड हो सकती है",



    "Only 4 images are allowed": "4 फोटो तक भेज सकते हैं",

    "Type something": "कुछ लिखें",


    "Type something to comment": "कुछ लिखें",

    "Please write something": "कुछ लिखें",

    // "Please write something":"कुछ लिखें",


    "Logged out Successfully": "लॉगआउट हुआ",

    "Spaark Deleted": "स्पार्क डिलीट हुआ ",

    "Spaarks Call available only on mobile app": "स्पार्क्स कॉल मोबाइल ऍप पर उपलब्ध है",
    "Call": "कॉल",

    "Are you sure?": "पक्का?",

    //"Are you sure to alias?":"पक्का?",

    // "Are you sure, you want to block this user?":"पक्का?",

    //  "Are you sure, you want to clear chat?":"पक्का?",


    //  "Are you sure you want to report?":"पक्का?",

    "Are you sure, you want to block this user?": "पक्का?",
    "Requests sent": "भेजे गए रिक्वेस्ट्स",

    //  "Do you really want to delete?":"पक्का?",

    "Are you seeking information?": "क्या आपको कुछ इनफार्मेशन चाहिए?",
    "ARE YOU SEEKING INFORMATION?": "क्या आपको कुछ इनफार्मेशन चाहिए?",
    "ARE YOU FACING ANY PROBLEM WITH APPLICATION?": "क्या ऍप इस्तेमाल करने में कोई परेशानी है?",

    "Are you facing any problem with application?": "क्या ऍप इस्तेमाल करने में कोई परेशानी है?",

    //Added on 28th june

    "Spaarks connects you to your local area wherever you go": "जहाँ जाएँ स्पार्क्स से आस पास कनैक्ट करें",

    "Connect to your local area": "अपने आस पास कनैक्ट करें",

    "Announce, Make Friends, Reach Customers, Promote Business, Find Work": "अनाउंस, फ्रैंड्स बनाएं, कस्टमर्स से जुड़ें, बिज़नेस प्रमोट, काम ढूँढें",
    "Friends": "फ्रैंड्स",
    "Create Spaark": "स्पार्क करें",

    "Make friends": "फ्रैंड्स बनाएं",
    "Make Friends": "फ्रैंड्स बनाएं",

    "Friend requests": "फ्रैंड रिक्वेस्ट",

    "Version": "वर्ज़न",
    "Market profile": "मार्केट प्रोफाइल",
    "Bookmarks": "बुकमार्क्स",

    "Watch Spaarks Tutorials": "स्पार्क्स टुटोरिअल्स देखें",
    "Tweet us on @Spaarks.Smiles": "हमें ट्वीट करें @Spaarks.Smiles",
    "Tag us @Spaarks_Smiles": "हमें टैग करें@Spaarks_Smiles",
    "Like us on Spaarks.Smiles": "हमें लाइक करें Spaarks.Smiles",

    "Open Spaarks on your mobile phone.": "अपने मोबाइल फ़ोन पर स्पार्क्स ऍप खोलें",
    "Open": "खुला है",
    "Exit": "बाहर निकलें",
    "Click on QR icon.": "QR आइकॉन पर क्लिक करें",

    "Scan this QR with you mobile phone.": "QR स्कैन करें",

    "No Images Available": "कोई इमेज मौजूद नहीं है",

    "No Spaarks Found": "कोई स्पार्क मौजूद नहीं है",
    "No Spaarks found with in": "में कोई स्पार्क मौजूद नहीं है",
    "No Spaarks found beyond": "आगे कोई स्पार्क नहीं मिला",
    "Save": "सेव",

    "Save & continue": "सेव & आगे",

    "Forward To": "फॉरवर्ड",

    "Change location": "लोकेशन बदलें",

    "Clear All": "सब मिटाएं",
    "Clear all": "सब मिटाएं",

    "Text field cannot be empty": "कुछ लिखें",

    //"Are you seeking information?":"क्या आपको कोई जानकारी चाहिए?",

    "Type your message here": "अपना मैसेज यहाँ लिखें",

    "Requests received": "मिले हुए रिक्वेस्ट्स",

    "No requests received": "कोई रिक्वेस्ट नहीं है",

    "Requests Sent": "भेजे गए रिक्वेस्ट्स",
    "Sent": "भेज दिया",
    "Received": "प्राप्त किया था",
    "Request to chat": "चैट रिक्वेस्ट भेजें",

    "Delete Friend Request": "फ्रैंड रिक्वेस्ट मिटाएं",
    "DELETE FRIEND REQUEST": "फ्रैंड रिक्वेस्ट मिटाएं",
    "IGNORE FRIEND REQUEST": "जाने दें",
    "No requests sent": "कोई रिक्वेस्ट नहीं भेजी",

    "YES": "",
    "NO": "",
    "OK": "",
    "You have reported a Content. Your details will remain confidential.": "आपने एक सामग्री की सूचना दी है। आपका विवरण गोपनीय रहेगा।",
    "You have already reported this Content.": "आप पहले ही इस सामग्री की रिपोर्ट कर चुके हैं।",
    "Arts": 'कला',
    "Beauty": 'ब्यूटी',
    "Consultant": 'कंसलटेंट',
    "Daily Services": 'दैनिक सेवाएं',
    "Donate": 'दान',
    "Education": 'शिक्षा',
    "Agri Mall": 'खेत का',
    "Agri Malls": 'खेत का',
    "Farm Fresh": 'खेत ताजा',
    "Fashion": 'फैशन',
    "Fitness": 'फिटनेस ',
    "Food": 'भोजन',
    "freelancer": 'फ्रीलांसर',
    "Health": 'स्वास्थय ',
    "Horoscope": 'भविष्य',
    "IT & Hardware": 'आईटी और हार्डवेयर ',
    "Lifestyle": 'लाइफस्टाइल',
    "Medical Care": 'मेडिकल केयर ',
    "Real Estate": 'रियल एस्टेट ',
    "Rent/Lease": 'किराये पर ',
    "Repair": 'रिपेयर',
    "Resell": 'रीसेल',
    "Stall": 'रेहड़ी खोखा',
    "Store": 'दुक़ान',
    "Travel/Transport": 'ट्रैवल और ट्रांसपोर्ट',
    "Travel & Transport": 'ट्रैवल और ट्रांसपोर्ट',

    "Worker": 'मजदूर',

    "Artist": 'कलाकार',
    "Handicrafts": 'हस्तकला ',
    "Lifestyle Coach": 'लाइफस्टाइल कोच',
    "Music Band": 'म्यूज़िक बैंड',
    "Music/Dance Tutor": 'म्यूज़िक/डांस टीचर',
    "Painter": 'पेंटर',
    "Photographer": 'फोटोग्राफर',
    "Massage": 'मालिश',
    "Salon": 'सैलून',
    "Stylist/Makeup": 'स्टाइलिस्ट/मेकअप ',
    "CA/Tax Consultant": 'सीऐ/टैक्स कंसलटेंट',
    "Career Counsellor": 'करियर सलाहकार ',
    "Dietician": 'डायटीशियन ',
    "Event Planner": 'इवेंट प्लानर',
    "Graphic Designer": 'ग्राफ़िक डिज़ाइनर ',
    "Interior Designer": 'इंटीरियर डिज़ाइनर',
    "Legal Consultant": 'लीगल कंसलटेंट',
    "Software Developer": 'सॉफ्टवेयर डेवलपर',
    "Carpenter": 'कारपेंटर',
    "Dhobi/Drycleaner": 'धोबी/ ड्राईक्लीन ',
    "Driver/Car-Washer": 'ड्राइवर/क्लीनर ',
    "Electrician": 'इलेक्ट्रीशियन',
    "Fruits/Vegetables": 'फल/सब्ज़ी ',
    "Garbage Collector": 'कचरावाला',
    "Gardener": 'माली',
    "General Store": 'जनरल स्टोर',
    "Gym": 'जिम',
    "Juice Corner": 'जूस सेंटर',
    "Maid/Cook": 'कामवाली/कुक',
    "Nurse/Caretaker": 'नर्स',
    "Pest Control": 'पैस्ट कण्ट्रोल',
    "Plumber": 'प्लम्बर',
    "Scrap Collector": 'रद्दीवाला',
    "Tailor": 'दर्ज़ी',
    "Tiffin": 'टिफ़िन',
    "Yoga": 'योगा',
    "Coaching Centre": 'कोचिंग सेंटर',
    "Institute": 'इंस्टिट्यूट ',
    "Sports Coach": 'स्पोर्ट्स कोच',
    "Tuition": 'ट्यूशन',
    "Tutor": 'टीचर',
    "Clothing": 'कपड़े',
    "Bakery": 'बेकरी',
    "Cafe/Parlour": 'कैफ़े / पार्लर',
    "Catering": 'केटरिंग',
    "Dhaba": 'ढाबा',
    "Home Based Food": 'घर का खाना ',
    "Panwala/Tea-stall": 'चाय/पानवाला',
    "Restaurant": 'रेस्टोरेंट',
    "Street Food": 'स्ट्रीट फ़ूड',
    "Sweet Shop": 'मिठाई दुकान ',
    "Beautician": 'ब्यूटिशियन',
    "Content Writer": 'लेखक',
    "Digital Marketing Expert": 'डिजिटल मार्केटिंग सलाहकार ',
    "IT Security": 'आईटी सिक्योरिटी',
    "Clinic": 'क्लिनिक',
    "Physiotherapist": 'फ़िज़ियोथेरेपिस्ट',
    "Broadband/DTH": 'ब्रॉडबैंड/डीटीएच',
    "Electricals": 'इलेक्ट्रिकल',
    "Electronics": 'इलेक्ट्रॉनिक्स',
    "Printing": 'प्रिंटिंग',
    "Medical Store": 'मेडिकल स्टोर',
    "Doctor": 'डॉक्टर',
    "Bag Repair": 'बैग रिपेयर',
    "Florist": 'फूलवाला ',
    "Key Maker": 'चाबीवाला',
    "Kitchenware": 'किचन सामान ',
    "Mechanic": 'मैकेनिक',
    "Shoe Repair": 'जूता ठीक',
    "Books/Stationery": 'बुक्स/स्टेशनरी',
    "Nursery": 'नर्सरी',
    "Toys": 'खिलोने',
    "Autorickshaw": 'ऑटोरिकशॉ',
    "Cab/Taxi": 'कैब/टैक्सी',
    "Packers & Movers": 'पैकर मूवर',
    "Vehicle for Rent": 'किराये पे गाड़ी',
    "Dainik Majdoor": 'दैनिक मजदूर',
    "Security Guard": 'सिक्योरिटी गार्ड',
    "Jeweller": 'सुनार',
    "Automobiles": 'ऑटोमोबाइल',
    "I give a Service": 'मुझसे सर्विस लीजिये',
    "I have Something to Sell": 'मुझसे कुछ खरीदें ',
    "Announce Something": 'कुछ अनाउंस कीजिये ',
    "Post a Job": 'जॉब पोस्ट करें ',
    "I Want a Job": 'मुझे जॉब चाहिए ',
    "I need a Service": 'मुझे कुछ सर्विस चाहिए ',
    "Others": 'अन्य',
    "others": 'अन्य',
    "other": "अन्य",
    "OTHER": "अन्य",
    "Later": "बाद में",
    "Sort": "छांटें",
    "invalid input": "अमान्य निवेश",
    // "Did you complete your work with":"क्या आपका काम इनके साथ ख़त्म हुआ -",
    "What is the concept of this application?": 'इस एप्लिकेशन का संकल्प क्या है? ',
    "Connect to people in your local area.": 'अपने आस पास के लोगो से कनैक्ट करना।',
    "What is a Spaark?": 'स्पार्क क्या है?',
    "A Spaark is the information posted by a user.": 'यूज़र की पोस्ट को स्पार्क कहेंगे।',
    "What are the features in the application?": 'इस एप्लिकेशन में क्या फीचर्स हैं?',
    "i.Announce  is about events, public announcements, ideas, thoughts, opinions, news, offers, celebrations, festivals, prayers etc in your local area. ii.Market is about promoting your Service, making customers in your local area. You can also share your Seller profile with others through Whatsapp. You can also connect with buyers of goods or services or find jobs or work around you.": 'i.बताएं फीचर आपके आस पास में घटनाओं, पब्लिक घोषणाओं, विचारों, समाचारों, समारोहों, त्योहारों, प्रार्थनाओं आदि के बारे में है।ii. बाजार फीचर से आप अपनी सर्विस को प्रमोट कर सकते हैं, अपने आस पास ग्राहक बना सकते हैं। अपनी सैलर प्रोफाइल भी व्हाट्सप्प पर शेयर कर सकते हैं। आप खरीददारों से कनेक्ट या कोई काम भी ढून्ढ सकते हैं।',
    "Why does the application take my location permissions?": 'एप्लिकेशन मेरी लोकेशन की अनुमति क्यों लेता है?',
    "Local area is defined by user’s actual location.": "यूज़र की लोकेशन के हिसाब से ऐप में आस पास के स्पार्क्स दिखेंगे। ",
    "What is the importance of radius shown on the map?": " मैप पर दिखाए गए घेरे का महत्व क्या है?",
    "Am I visible to others on the map when I log into the app?": " क्या मेरे लॉगिन करते ही अन्य यूज़र्स मुझे देख सकते हैं?",
    "No. Others can see your Spaark’s location if you allow it, but not your location.": "नहीं। आपकी लोकेशन कोई नहीं देख सकता। आपकी स्पार्क की लोकेशन यदि आपने अनुमति दी थी तो देखी जा सकती है।",
    "Will other user's location be visible to me?": " क्या अन्य उपयोगकर्ताओं की लोकेशन मुझे दिखाई देगी?",
    "What if I want my Spaark to be visible for more distance?": "क्या मैं अपने स्पार्क को अधिक समय और घेरे में दिखा सकता हूँ?",
    "Radius gives the distance up to which you can see other Spaarks.": "जहाँ तक घेरा होगा वहाँ तक के स्पार्क्स दिखेंगे।",
    "No": "ना",
    "No.": "नहीं।",
    "Your session has been expired,Please login!": "टाइम समाप्त हो गया है। फिर से लॉगिन करें।",
    "No images posted yet.": "अभी तक कोई इमेज पोस्ट नहीं की गयी है",
    "Send request": "रिक्वेस्ट भेजें",
    "Leave a Business query with us.": "हमारे पास एक बिज़नेस प्रश्न छोड़ें।",
    "If Reports to a Spaark exceed a threshold level, it gets taken down automatically.": "यदि एक स्पार्क पर रिपोर्ट्स एक सीमा से ऊपर हो जाती हैं तो स्पार्क अपने आप ऐप से हट जाता है।",
    "If I am a Seller, then how do I collect reviews for my service from buyers?": "मैं अपनी सेवा के लिए खरीदार से रिव्यु कैसे लूँ?",
    "A Seller can collect a review from a user who got connected through Spaarks app. App will automatically direct both the users once a user connects a Seller.": "यदि एक यूज़र ऐप से किसी सैलर को कॉन्टैक्ट करता है तो ऐप इन दोनों यूज़र्स को अपने आप रिव्यु देने के लिए गाइड करेगी।",
    "How can I give review to a Seller?": "मैं एक सैलर को रिव्यु कैसे दूँ?",
    "As a buyer if you have connected to a Seller, then the Seller will send you the request for giving review.": "यदि आपने ऐप से एक सैलर को कॉन्टैक्ट किया है तो ऐप आपसे अपने आप सैलर के लिए रिव्यु मांग लेगी।",
    "No. You cannot edit your Spaark after posting it. You can always delete it.": "नहीं।स्पार्क पोस्ट करने के बाद बदला नहीं जा सकता। डिलीट कर सकते हैं।",
    "Can I edit my Spaark?": "क्या मैं अपने स्पार्क में कुछ बदल सकता हूँ?",
    "How is a Spaark or a Content taken down?": "एक स्पार्क या टिप्पणी ऐप से खुद ब खुद कैसे हटती है?",
    "How does an account get suspended?": "एक अकाउंट सस्पैंड कैसे होता है?",
    "An account whose Content is reported and taken down many times which exceeds the threshold level, the account gets suspended automatically.": "यदि एक अकाउंट के काफी स्पार्क्स रिपोर्ट होते हैं तो वह अकाउंट अपने आप सस्पैंड हो जाता है।",
    "What is the maximum video size allowed to upload?": " ज़्यादा से ज़्यादा कितनी बड़ी वीडियो अपलोड कर सकते हैं?",
    "50 MB - 1 video.": "50 एम् बी - 1 वीडियो",
    "Will I be able to receive calls when I have logged out.": "क्या मैं लॉग आउट होने पर कॉल प्राप्त कर सकूंगा?",
    "A user need to be logged into the app to receive the calls.": "कॉल प्राप्त करने के लिए आपको लॉग इन होना चाहिए।",
    "Can I recover a deleted chat?": "क्या मैं मिटाए गए चैट को फिर से प्राप्त कर सकता हूं?",
    "No. You cannot recover the chat, once deleted.": "नहीं, चैट मिटाने के बाद आप चैट को फिर से प्राप्त नहीं कर सकते।",
    "What happens when I exit a chat?": "जब मैं चैट से बाहर निकलता हूं तो क्या होता है?",
    "None of the users can exchange messages. You can resume the chat even after exiting.": "चैट से बाहर निकलने के बाद मेसेजस नहीं भेजे जा सकते। चैट को फिर से शुरू, मतलब रिज्यूम, भी किया जा सकता है।",
    "What will be visible to the other user when I block him/her?": "एक यूज़र को ब्लॉक करने पर उसे मेरे बारे में क्या दिखेगा?",
    "Your details will remain confidential. Your Spaarks will not be shown to the blocked user. The blocked user can not chat with you any further.": "आपकी जानकारी छुपी रहेगी। आपके स्पार्क्स ब्लॉक हुए यूज़र को नहीं दिखेंगे। ब्लॉक हुआ यूज़र आपके साथ चैट नहीं कर पाएगा।",
    "Copied to clipboard": "कॉपी हुआ. कहीं पेस्ट करें.",
    "Business enquires": "बिज़नेस प्रश्न",
    "You have not bookmarked any post yet.": "आपने अभी कोई पोस्ट बुकमार्क नहीं किया है।",
    "Post a Spaark": "स्पार्क पोस्ट करें ",
    "Post Spaark": "पोस्ट स्पार्क",
    "Terms and policies": "टर्म्स पॉलिसीज़",
    "Find Date": "डेट खोजें",
    "Local News": "लोकल न्यूज़",
    "You have not blocked anyone yet.": "आपने अभी किसी को ब्लॉक नहीं किया है।",
    "Couldn't find your query ?": "आपका सवाल नहीं मिला?",
    "List of your spaarks for which you received requests.": "आपके स्पार्क्स और उन पर मिली रिक्वेस्ट।",
    "Yes": "हाँ",
    "Jobs": "जॉब्स",
    "Events": "इवेंट्स",
    "Bookmarked successfully": "बुकमार्क हुआ",
    "Removed Successfully": "मिटाया गया",
    "Bookmark removed": "बुकमार्क मिटाया",
    "Make a call": "कॉल करें",
    "MAKE A CALL": "कॉल करें",
    "Normal call": "फ़ोन से कॉल",
    "Owner of this Spaark disabled Spaarks call.": "यूज़र ने स्पार्क्स कॉल बंद किया हुआ है",
    "Owner of this Spaark disabled Normal call.": "यूज़र ने फ़ोन से कॉल बंद किया हुआ है",
    "Owner of this Spaark disabled": "यूज़र ने",
    "option": "ऑप्शन बंद किया हुआ है",
    "This option is available when you create a spaark": "यह ऑप्शन तब उपलब्ध होता है जब आप एक स्पार्क बनाते हैं",
    "Make call from your personal number.": "अपने नंबर से कॉल करें",
    "This clears entire chat with the user.": "यूज़र के साथ की गयी पूरी चैट मिट जाती है",
    "Note : You can also disable Spaarks call while posting a Spaark": "नोट: आप भी स्पार्क पोस्ट करते हुए स्पार्क्स कॉल बंद कर सकते हैं।",
    "This will not allow the other user to chat with you. You can still see each others spaarks.": "यूज़र आपके साथ चैट नहीं कर पाएगा। यूज़र के स्पार्क देख सकेंगे।",
    "Click to send message": "मैसेज भेजने के लिए क्लिक करें",
    "You are anonymous to this user.": "आप इस उपयोगकर्ता के लिए गुमनाम हैं।",
    "You don’t have any bookmarks yet": "आपके पास अभी तक कोई बुकमार्क नहीं है",
    "Choose your language": "भाषा चुनें",
    "Payment related issues?": "भुगतान सम्बन्धी",
    "Payment Related issues?": "भुगतान सम्बन्धी",
    "No Notifications.": "कोई नोटिफिकेशन्स नहीं",
    "You have no notifications yet.": "कोई नोटिफिकेशन्स नहीं",
    "ACCEPT FRIEND REQUEST": " फ्रैंड रिक्वेस्ट स्वीकार करें",
    "BUSINESS ENQUIRIES": "बिज़नेस इन्क्वारी",
    "Business enquiries": "बिज़नेस इन्क्वारी",
    "List of spaarks to which you sent requests": "स्पार्क्स और उन पर भेजी गयी रिक्वेस्ट",
    "Pending": "इंतजार में.",
    "No results found": "नो रिजल्ट फाउंड",
    "Search in": "की खोज में",
    "No spaarks created.": "कोई स्पार्क्स नहीं बनाई।",
    "commented on Your Spaark.": "इस स्पार्क पर टिप्पणी की",
    "Oops! Without location you cannot use this application. Refresh or grant location permission.": "ऍप को इस्तेमाल करने के लिए लोकेशन ज़रूरी है। रिफ्रेश करें या लोकेशन परमिशन दें।",
    "Max 10 images can be uploaded.": "एक बार में 10 इमेज ही अपलोड कर सकते हैं।",
    "Max 10 files can be uploaded.": "एक बार में 10 फाइल ही अपलोड कर सकते हैं।",
    "Media devices fetching failed": "कुछ समस्या है. रिफ्रेश करें।",
    "You can not resend OTP yet.": "अभी फिर से OTP नहीं भेज सकते",
    "Name/Business Name. Should be less than 20 characters.": "नाम/बिज़नेस नाम. 20 अक्षर से कम।",
    "Name/Business Name": "नाम/बिज़नेस नाम",
    "select only one video": "केवल 1 वीडियो चुनें",
    "No contacts in your forward list.": "फॉरवर्ड करने ले लिए कोई कॉन्टैक्ट नहीं।",
    "Reply to Enquiry sent": "रिप्लाई करें",
    "Your request is pending with the user.": "आपकी रिक्वेस्ट यूज़र के पास इंतज़ार में है।",
    "You have Entered Wrong OTP": "OTP गलत है",
    "Name can not be empty": "नाम लिखें",
    "Atleast 1 character should be there": "कम से कम 1 अक्षर",
    "Name should not contain Anonymous or anonymous": "नाम Anonymous नहीं हो सकता।",
    "Please wait for user to accept your requests": "यूज़र द्वारा आपकी रिक्वेस्ट स्वीकार करने की प्रतीक्षा करें",
    "Request has been deleted": "रिक्वेस्ट मिटाई गयी",
    "It's your own Spaark.": "यह आपका ही स्पार्क है",
    "You have already requested this user, please go to requests and check": "इस यूज़र को आप पहले ही रिक्वेस्ट भेज चुके हैं. रिक्वेस्ट्स में जाकर देख सकते हैं.",
    "Please login to block": "ब्लॉक करने के लिए लॉगिन करें",
    "Please login to like post": "पोस्ट लाइक करने के लिए लॉगिन करें",
    "choose at least one preference.": "कम से कम एक विकल्प चुनें।",
    "Please check your internet connection": "अपना इंटरनेट चैक करें",
    "Services offered": "सर्विस",
    "You already have this user in your list": "यह यूज़र पहले से आपकी लिस्ट में है",
    "Please login to report": "रिपोर्ट करने के लिए लॉगिन करें",
    "Type something to send request": "कुछ लिखें",
    "Request has been sent successfully": "रिक्वेस्ट भेजी गयी",
    "Request has been Accepted": "रिक्वेस्ट स्वीकार हो गयी",
    "minimum length is 3": "कम से कम 3 अक्षर",
    "Minimum 3 characters are allowed": "कम से कम 3 अक्षर",
    "Calls Available only on mobile Browsers": "कॉल मोबाइल ब्राउज़र पर उपलब्ध है",
    "Chat request details": "चैट रिक्वेस्ट का विवरण",
    "Chat request": "चैट रिक्वेस्ट",
    "No contacts in your forward list !": "फॉरवर्ड करने ले लिए कोई कॉन्टैक्ट नहीं.",
    "Add image": "फोटो जोड़ें",
    "Add an image": "फोटो जोड़ें",
    "Stylist, Electrician,Dhobi, Gardener, Repair etc.": "स्टाइलिस्ट, इलेक्ट्रीशियन, धोबी, माली, रिपेयर,",
    "people": "लोगो",
    "People": "लोगो",
    "Maid, Driver, Plumber, Tuition, Freelancer etc.": "कामवाली, ड्राइवर, प्लम्बर, ट्यूशन,  फ्रीलांसर,",
    "Fruits/Vegetables, Handicrafts, Homemade, Agri Mall etc.": "फल/सब्ज़ी, हस्तकला, होममेड, खेत का",
    "Say Hello, Connect to a Stranger, Find a Date.": "हैलो कहें, अजनबी से जुड़ें,डेट खोजें",
    "Public Announcements, Events, Festivals, Launch, Party.": "पब्लिक घोषणाओं, घटनाओं, त्योहारों, लॉन्च, पार्टी",
    "Labour, Assistant, Professional etc.": "लेबर, असिस्टेंट,पेशेवर",
    "Skilled, Not Skilled, Part Time etc.": "कुशल, अकुशल, पार्ट टाइम",
    "Health Emergency, Ask for Help, Lost or Found etc.": "मदद पूछें,स्वास्थ्य आपातकाल,लॉस्ट और फाउंड",
    "Job": "जॉब",
    "Want work": "काम चाहिए",
    "Want Work": "काम चाहिए",
    "Work": "काम",
    "Freelancer": "फ्रीलांसर",
    "New Comment": "नया कमैंट",
    "Your comment has been reported.": "आपका कमैंट रिपोर्ट किया गया",
    "Spaark Reported": "स्पार्क रिपोर्ट किया गया",
    "No services offered yet.": "अभी तक कोई सर्विस प्रदान नहीं की गई है।",
    "Market profile gets created when spaarks are posted in market category.": "मार्केट कैटेगरी में स्पार्क्स पोस्ट किए जाने पर मार्केट प्रोफाइल बन जाता है।",
    "Need": "जरुरत",
    "Something went wrong": "कुछ गलत हो गया!",
    "Team spaarks": "",
    "Spaark anonymously": "गुमनाम स्पार्क करें",
    "Explore now": "एक्स्प्लोर करें",
    "The way of connection you choose now, will always remain same with this user.": "आप पहली बार यूज़र से जिस तरह का कनेक्शन रखेंगे, वह हमेशा वैसा ही रहेगा।",
    "To start chat go to any spaark in make friends and click on request to chat.For anonymous chat turn off your name visibility while sending request to chat.": "चैट शुरू करने के लिए फ्रेंड्स फीचर में किसी भी स्पार्क पर जाएँ और चैट का अनुरोध भेजें। गुमनाम चैट के लिए अनुरोध भेजते हुए अपने नाम को छुपाएं।",
    "Simply post an anonymous spaark for other users around you to see by clicking here.": "आप भी गुमनाम स्पार्क पोस्ट कर सकते हैं। यहाँ क्लिक करें।",
    "This message has been deleted": "यह मैसेज डिलीट हो गया है",
    "Only available on mobile app": "मोबाइल ऍप पर उपलब्ध",
    "Chat cannot be replied anymore.": "आगे चैट नहीं हो सकती",
    "Allows other to make a regular call to you": "कोई आपको नॉर्मल फ़ोन कॉल कर सकता है",
    "Please login to bookmark profile": "प्रोफाइल बुकमार्क करने के लिए लॉगिन करें।",
    "Please login to bookmark post": "पोस्ट बुकमार्क करने के लिए लॉगिन करें।",
    "View all": "सभी देखें",
    "View less": "कम देखें",
    "Please rate this provider": "कृपया इस प्रदाता को रेट करें",
    "Based upon your response, we will approach the user to give you rating and review.": "आपके जवाब के हिसाब से हम यूज़र से आपके लिए रेटिंग और रिव्यु लेंगे",
    "Team Spaarks": "टीम स्पार्क्स",
    "One last step": "एक आखिरी स्टैप",
    "Mumbai": "मुंबई",
    "Mumbai (or) Bombay": "मुंबई",
    "Delhi": "दिल्ली",
    "Bengaluru": "बैंगलोर",
    "Bangalore (or) Bengaluru": "बैंगलोर",
    "Hyderabad": "हैदराबाद",
    "Ahmedabad": "अहमदाबाद",
    "Ahmadabad (or) Ahmedabad": "अहमदाबाद",
    "Chandigarh": "चंडीगढ़",
    "Chennai": "चेन्नई",
    "Chennai (or) Madras": "चेन्नई",
    "Kolkata": "कोलकाता",
    "Kolkata (or) Calcutta": "कोलकाता",
    "Pune": "पुणे",
    "Sūrat": "सूरत",
    "Lucknow": "लखनऊ",
    "Jaipur": "जयपुर",
    "Cawnpore(or) Kanpur": "कानपुर",
    "Mirzāpur": "मिर्जापुर",
    "Mirzapur": "मिर्जापुर",
    "Nāgpur": "नागपुर",
    "Ghāziābād": "गाज़ियाबाद",
    "Indore": "इंदौर",
    "Vadodara": "वडोदरा",
    "Vishākhapatnam (or) Vizag": "विशाखापत्तनम",
    "Bhopāl": "भोपाल",
    "Chinchvad (or) Chinchwad": "चिंचवड",
    "Patna": "पटना",
    "Ludhiāna": "लुधियाना",
    "Āgra": "आगरा",
    "Kalyān": "कल्याणी",
    "Madurai": "मदुरै",
    "Jamshedpur": "जमशेदपुर",
    "Nāsik (or) Nashik": "नासिक",
    "Nasik (or) Nashik": "नासिक",
    "Nashik": "नासिक",
    "Farīdābād": "फरीदाबादी",
    "Aurangābād": "औरंगाबादी",
    "Rājkot": "राजकोटी",
    "Meerut": "मेरठ",
    "Jabalpur": "जबलपुर",
    "Thāne": "थाइन",
    "Dhanbād": "धनबादी",
    "Allahābād": "इलाहाबाद",
    "Vārānasi": "वाराणसी",
    "Srīnagar": "श्रीनगर",
    "Amritsar": "अमृतसर",
    "Alīgarh": "अलीगढ़",
    "Bhiwandi": "भिवंडी",
    "Gwalior": "ग्वालियर",
    "Bhilai": "भिलाई",
    "Hāora": "हाओरां",
    "Rānchi": "रांची",
    "Bezwāda": "बेजवाद:",
    "Chandīgarh": "चंडीगढ़",
    "Mysore": "मैसूर",
    "Raipur": "रायपुर",
    "Kota": "कोटा",
    "Bareilly": "बरेली",
    "Jodhpur": "जोधपुर",
    "Coimbatore": "कोयंबटूर",
    "Dispur": "दिसपुर",
    "Guwāhāti": "गुवाहाटी",
    "Solāpur": "सोलापुर",
    "Trichinopoly": "त्रिचिनोपोली",
    "Hubli": "हुबली",
    "Jalandhar": "जालंधर",
    "Bhubaneshwar (or) Bhubaneswar": "भुवनेश्वर",
    "Bhayandar": "भयंदर",
    "Morādābād": "मुरादाबाद",
    "Kolhāpur": "कोल्हापुरी",
    "Thiruvananthapuram": "तिरुवनंतपुरम",
    "Sahāranpur": "सहारनपुर",
    "Warangal": "वारंगल",
    "Salem": "सलेम",
    "Mālegaon": "मालेगांव",
    "Kochi": "कोच्चि",
    "Gorakhpur": "गोरखपुर",
    "Shimoga": "शिमोगा",
    "Tiruppūr": "तिरुपूरी",
    "Guntūr": "गुंटूर",
    "Raurkela": "राउरकेला",
    "Mangalore": "मंगलौर",
    "Nānded": "नांदेड़",
    "Cuttack": "कटक",
    "Chānda (or) Chandrapur": "चंद्रपुर",
    "Dehra Dūn": "देहरादून",
    "Durgāpur": "दुर्गापुर",
    "Āsansol": "आसनसोल",
    "Bhāvnagar": "भावनगर",
    "Amrāvati": "अमरावती",
    "Amravati": "अमरावती",
    "Nellore": "नेल्लोर",
    "Ajmer": "अजमेर",
    "Tinnevelly": "टिननेवेली",
    "Bīkaner": "बीकानेर",
    "Agartala": "अगरतला",
    "Ujjain": "उज्जैन",
    "Jhānsi": "झांसी",
    "Ulhāsnagar": "उल्हासनगर",
    "Davangere": "दावणगेरे",
    "Jammu": "जम्मू",
    "Belgaum": "बेलगाम",
    "Gulbarga": "गुलबर्गा",
    "Gulbarga (or) Kalaburagi": "गुलबर्गा (या) कलबुर्गी",
    "Or": "या",
    "Jāmnagar": "जामनगर",
    "Dhūlia": "धूलिया",
    "Gaya": "गया",
    "Jalgaon": "जलगांव",
    "Kurnool": "कुरनूल",
    "Udaipur": "उदयपुर",
    "Bellary": "बेल्लारी",
    "Sāngli": "सांगली",
    "Tuticorin": "तूतीकोरिन",
    "Calicut": "कालीकट",
    "Akola": "अकोला",
    "Bhāgalpur": "भागलपुर",
    "Sīkar": "शिकार",
    "Tumkūr": "तुमकुर",
    "Quilon": "क्विलोन",
    "Muzaffarnagar": "मुज़फ्फरनगर",
    "Bhīlwāra": "भीलवाड़ा",
    "Nizāmābād": "निजामाबाद",
    "Bhātpāra": "भतपारा",
    "Kākināda": "काकीनाडा",
    "Parbhani": "परभनी",
    "Pānihāti": "पानीहाटी",
    "Lātūr": "लातूर",
    "Rohtak": "रोहतक",
    "Rājapālaiyam": "राजपालियम",
    "Ahmadnagar": "अहमदनगर",
    "Cuddapah": "कडप्पा",
    "Kadapa": "कडप्पा",
    "Rājahmundry": "राजमुंदरी",
    "Alwar": "अलवाडी",
    "Muzaffarpur": "मुजफ्फरपुर",
    "Bilāspur": "बिलासपुर",
    "Mathura": "मथुरा",
    "Kāmārhāti": "कमरहटी",
    "Saugor": "सागर",
    "Bijāpur (or) Vijayapura": "बीजापुर (या) विजयपुरा",
    "Brahmapur (or) Berhampur": "ब्रह्मपुर (या) बेरहामपुर",
    "Shāhjānpur": "शहजानपुर",
    "Trichūr  (or) Thrissur": "त्रिचूर (या) त्रिशूर",
    "Barddhamān": "बर्द्धमान",
    "Sambalpur": "संबलपुर",
    "Purnea": "पूर्णिया",
    "Hisar": "हिसार",
    "Fīrozābād": "फिरोजाबाद",
    "Bīdar": "बीदर",
    "Rāmpur": "रामपुर",
    "Shiliguri": "सिलिगुरी",
    "Bāli": "बाली",
    "Pānīpat": "पानीपत",
    "Karīmnagar": "करीमनगर",
    "Bhuj": "भुज",
    "Ichalkaranji": "इचलकरंजी",
    "Tirupati": "तिरुपति",
    "Hospet": "होसपेट",
    "Āīzawl": "आइजोल",
    "Sannai": "सन्नाई",
    "Bārāsat": "बरसात",
    "Ratlām": "रतलाम",
    "Handwāra": "हंदवाड़ा",
    "Drug": "दुर्ग",
    "Imphāl": "इंफाल",
    "Anantapur (or) Anantapuram": "अनंतपुर (या) अनन्तपुरम",
    "Etāwah": "इटावा",
    "Rāichūr": "रायचुर",
    "Ongole": "ओंगोल",
    "Bharatpur": "भरतपुर",
    "Begusarai": "बेगूसराय",
    "Sonīpat": "सोनीपत",
    "Rāmgundam": "रामगुंडम",
    "Hāpur": "हापुड़",
    "Uluberiya": "उलुबेरिया",
    "Porbandar": "पोरबंदर",
    "Pāli": "पाली",
    "Vizianagaram": "विजयनगरम",
    "Puducherry(or) Pondicherry": "पुडुचेरी (या) पांडिचेरी",
    "Karnāl": "करनाल",
    "Nāgercoil": "नागरकोइल",
    "Tanjore": "तंजौर",
    "Sambhal": "संभल",
    "Shimla": "शिमला",
    "Ghāndīnagar": "गांधीनगर",
    "Shillong": "शिलांग",
    "New Delhi": "नई दिल्ली",
    "Port Blair": "पोर्ट ब्लेयर",
    "Gangtok": "गंगटोक",
    "Kohīma": "कोहिमा",
    "Itānagar": "ईटानगर",
    "Panaji": "पणजी",
    "Damān": "दमन",
    "Kavaratti": "कवरत्ती",
    "Panchkula": "पंचकुला",
    "Kagaznāgār": "कागजनगर",
    "Adoni": "अदोनी",
    "Alappuzha": "अलपुझा",
    "Ambala": "अंबाला",
    "Ambattur": "अंबात्तुर",
    "Amroha": "अमरोहा",
    "Anand": "आनंद",
    "Arrah": "आरा",
    "Avadi": "अवादी",
    "Bahraich": "बहराइच",
    "Ballia": "बलिया",
    "Bally": "बाली",
    "Baranagar or Baranagore": "बारानगर या बरनागोर",
    "Bathinda": "बठिंडा",
    "Bettiah": "बेतिया",
    "Bhalswa Jahangir Pur": "भलस्वा जहांगीर पुर",
    "Bhimavaram": "भीमावरम",
    "Bhind": "भिंड",
    "Bhiwani": "भिवानी",
    "Bhusawal": "भुसावली",
    "Bidhannagar": "बिधाननगर",
    "Bihar Sharif": "बिहारशरीफ",
    "Bokaro": "बोकारो",
    "Bongaigaon": "बोंगईगांव",
    "Bulandshahr": "बुलंदशहर",
    "Burhanpur": "बुरहानपुर",
    "Buxar": "बक्सर",
    "Chapra": "छपरा",
    "Chittoor": "चित्तूर",
    "Danapur": "दानापुर",
    "Darbhanga": "दरभंगा",
    "Dehri": "डेहरी",
    "Deoghar": "देवघर",
    "Dewas": "देवास",
    "Dharmavaram": "धर्मावरम",
    "Dhule": "धुले",
    "Dibrugarh": "डिब्रूगढ़",
    "Dindigul": "डिंडीगुल",
    "Erode": "इरोड",
    "Farrukhabad": "फर्रुखाबाद",
    "Fatehpur": "फतेहपुर",
    "Gandhidham": "गांधीधाम",
    "Giridih": "गिरिडीह",
    "Gopalpur": "गोपालपुर",
    "Gudivada": "गुड़ीवाड़ा",
    "Guna": "गुना",
    "Guntakal": "गुंतकल",
    "Hajipur": "हाजीपुर",
    "Haridwar": "हरिद्वार",
    "Hazaribagh": "हजारीबाग",
    "Hindupur": "हिन्दुपुर",
    "Hosur": "होसुर",
    "Howrah": "हावड़ा",
    "Hubli–Dharwad": "हुबली-धारवाड़",
    "Jalna": "जलना",
    "Jamalpur": "जमालपुर",
    "Jaunpur": "जौनपुर",
    "Jehanabad": "जहानाबाद",
    "Jorhat": "जोरहाट",
    "Ludhiana": "लुधियाना",
    "Surat": "सूरत",
    "Junagadh": "जूनागढ़",
    "Kalyan-Dombivli": "कल्याण-डोंबिवली",
    "Kalyan": "कल्याण",
    "Karaikudi": "कराइकुडी",
    "Karawal Nagar": "करावल नगर",
    "Nagpur": "नागपुर",
    "Varanasi": "वाराणसी",
    "Katihar": "कटिहार",
    "Katni": "कटनी",
    "Kavali": "कवाली",
    "Khandwa": "खंडवा",
    "Kharagpur": "खड़गपुर",
    "Khora-Ghaziabad\"": "खोरा-गाजियाबाद",
    "Ghaziabad": "गाजियाबाद",
    "Thane": "थाइन",
    "Bhopal": "भोपाल",
    "Kirari Suleman Nagar": "किरारी सुलेमान नगर",
    "Kishanganj": "किशनगंज",
    "Kollam": "कोल्लम",
    "Kottayam": "कोट्टायम",
    "Kozhikode": "कोझिकोड",
    "Kumbakonam": "कुंभकोणम",
    "Loni": "लोनी",
    "Machilipatnam": "मछलीपट्टनम",
    "Madanapalle": "मदनपल्ली",
    "Madhyamgram": "मध्यमग्राम",
    "Mahbubnagar": "महबूबनगर",
    "Maheshtala": "महेशताल",
    "Malda": "मालदा",
    "Mau": "मौ",
    "Medininagar": "मेदिनीनगर",
    "Daltonganj": "डाल्टनगंज",
    "Mehsana": "मेहसाणा",
    "Mira-Bhayandar": "मीरा-भयंदरी",
    "Miryalaguda": "मिर्यालागुदा",
    "Morbi": "मोरबी",
    "Morena": "मुरैना",
    "Motihari": "मोतिहारी",
    "Munger": "मुंगेर",
    "Nadiad": "नाडियाड",
    "Nagaon": "नगांव",
    "Naihati": "नैहाटी",
    "Nandyal": "नांदयाल",
    "Nangloi Jat": "नांगलोई जाति",
    "Narasaraopet": "नरसरावपेटी",
    "Noida": "नोएडा",
    "North Dumdum": "उत्तर दमदम",
    "Orai": "उरई",
    "Pallavaram": "पल्लावरम",
    "Panvel": "पनवेल",
    "Phagwara": "फगवाड़ा",
    "Phusro": "फुसरो",
    "Pimpri-Chinchwad": "पिंपरी-चिंचवड",
    "Proddatur": "प्रोद्दातुर",
    "Pudukkottai": "पुदुक्कोट्टई",
    "Purnia": "पूर्णिया",
    "Raebareli": "रायबरेली",
    "Raiganj": "रायगंज",
    // "Raipur":""
    "Rajpur Sonarpur": "राजपुर सोनारपुर",
    "Ramgarh": "रामगढ़",
    "Raurkela Industrial Township": "राउरकेला औद्योगिक टाउनशिप",
    "Rewa": "रेवा",
    "Sagar": "सागर",
    "Saharsa": "सहरसा",
    "Satara": "सतारा",
    "Satna": "सतना",
    "Secunderabad": "सिकंदराबाद",
    "Serampore": "श्रीरामपुर",
    "Shivpuri": "शिवपुरी",
    "Silchar": "सिलचर",
    "Singrauli": "सिंगरौली",
    "Sirsa": "सिरसा",
    "Siwan": "सिवान",
    "South Dumdum": "दक्षिण दमदम",
    "Sri Ganganagar": "श्री गंगानगर",
    "Srikakulam": "श्रीकाकुलम",
    "SultanPur Majra": "सुल्तानपुर मजरा",
    "Surendranagar Dudhrej": "सुरेंद्रनगर दुधरेजी",
    "Suryapet": "सूर्यापेट",
    "Tadepalligudem": "ताडेपल्लीगुडेम",
    "Tadipatri": "ताडिपत्रि",
    "Tenali": "तेनाली",
    "Tezpur": "तेजपुर",
    "Thanjavur": "तंजावुरी",
    "Thoothukudi": "थूथुकुडो",
    "Tinsukia": "तिनसुकिया",
    "Aurangabad": "औरंगाबाद",
    "Amaravati": "अमरावती",
    "Yamunanagar": "यमुनानगर",
    "Vijayawada (or) Bezawada": "विजयवाड़ा (या) बेजवाड़ा",
    "Tiruvannamalai": "तिरुवन्नामलाई",
    "Tirur": "तिरूर",
    "Berhampore (or) Baharampur or Berhampur": "बेरहामपुर (या) बहरामपुर या बरहामपुर",
    "Chinsurah (or) Chuchura": "चिसुराह (या) चुचुरा",
    "Eluru (or) Ellore": "एलुरु (या) एलोर",
    "Gurgaon (or) Gurugram": "गुड़गांव (या) गुरुग्राम",
    "Khammam (or) Khammamett": "खम्मम (या) खम्ममेट",
    "नवी मुंबई (या) न्यू बॉम्बे": "नवी मुंबई (या) न्यू",
    "Sasaram (or) Sahasram": "सासाराम (या) सहस्राम",
    "Tiruchirappalli (or) Tiruchi (or) Trichy": "तिरुचिरापल्ली (या) तिरुचि (या) त्रिची",
    "Bokaro Steel City": "बोकारो स्टील सिटी",
    "Goa": "गोवा",
    "Hamirpur": "हमीरपुर",
    "Haora": "होरा",
    "Kannur": "कन्नूर",
    "Malappuram": "मलप्पुरम",
    "Palakkad": "पलक्कड़",
    "Perinthalmanna": "पेरिन्तल्मन्न",
    "Purulia": "पुरुलिया",
    "Tirunelveli": "तिरुनेलवेली",
    "Tiruvottiyur": "तिरुवोत्तीयुर",
    "Udupi": "उडुपी",
    "Unnao": "उन्नाव",
    "Uzhavarkarai": "उझावरकराई",
    "Marie Oulgaret": "मैरी औल्गरेटा",
    "Vasai-Virar": "वसई-विरार",
    "Vasco Da Gama": "वास्को डिगामा",
    "Vellore": "वेल्लोर",
    "Navi Mumbai (or) New Bombay": "नवी मुंबई (या) न्यू बॉम्बे",
    "Patiala": "पटियाला",
    "Kulti": "कुल्टी",
    "Allahabad": "इलाहाबाद",
    "Moradabad": "मुरादाबाद",
    "Rate service provider/seller": "सेवा प्रदाता/विक्रेता को रेट करें",
    "Response recorded. Thank you.": "जवाब दर्ज की गई। धन्यवाद",
    "Phone number": "फ़ोन नंबर",
    "Gender": "लिंग",
    "Male": "पुरुष",
    "Resume chat": "चैट फिर से शुरू करें",
    "Agents": "एजेंट्स",
    "Financial Services": "फिनांशल सर्विसेज",
    "You cannot reply to this chat": "आप इस चैट का जवाब नहीं दे सकते",
    "Unblocked successfully.": "सफलतापूर्वक अनब्लॉक किया गया",
    "Blocked successfully.": "सफलतापूर्वक ब्लॉक किया गया",
    "Redirection Enabled for newly created tickets.": "नए बनाए गए टिकटों के लिए पुनर्निर्देशन सक्षम।",
    "Hardware": "हार्डवेयर",
    "Telecom": "टेलीकॉम",
    "Furniture": "फर्नीचर",
    "Construction": "निर्माण",
    "Footwear": "फुटवियर",
    "Landscape": "लैंडस्केप",
    "error encountered": "त्रुटि का सामना करना पड़ा",
    "You Cannot have more than two active sessions at a time. please logout of one session from your mobile app ": "आपके पास एक समय में दो से अधिक सक्रिय सत्र नहीं हो सकते हैं। कृपया अपने मोबाइल ऐप से एक सत्र का लॉगआउट करें",
    "Audio": "ऑडियो",
    "File": "फाइल",
    "Photo": "फोटो",
    "Video": "वीडियो",
    "You have a notification": "आपके पास एक सूचना है",
    "click to view": "देखने के लिए क्लिक करें",
    "New Notification": "नई अधिसूचना",
    "Someone has commented on your post.": "किसी ने आपकी पोस्ट पर टिप्पणी की है।",
    "Comment Reported": "रिपोर्ट की गई टिप्पणी",
    "Bookmark removed successfully": "बुकमार्क मिटाया गया",
    "Add Nickname": "उपनाम जोड़ें",
    "Adds Fun. Helps you remember anonymous users.Only visible to you.": "मज़ा जोड़ता है। गुमनाम उपयोगकर्ताओं को याद रखने में आपकी सहायता करता है। केवल आपको दिखाई देता है।",
    "Bezwada": "बेजवाड़ा",
    "Bhavnagar": "भावनगर",
    "Bikaner": "बीकानेर",
    "Nizamabad": "निजामाबाद",
    "Bhagalpur": "भागलपुर",
    "Bhilwara": "भीलवाड़ा",
    "Bilaspur": "बिलासपुर",
    "Chanda (or) Chandrapur": "चंदा (या) चंद्रपुर",
    "Nagercoil": "नागरकोइल",
    "Trichur  (or) Thrissur": "त्रिचूर (या) त्रिशूर",
    "Ranchi": "रांची",
    "Raichur": "रायचुर",
    "Nanded": "नांदेड़",
    "Dehra Dun": "देहरादून",
    "Malegaon": "मालेगांव",
    "Firozabad": "फिरोजाबाद",
    "Faridabad": "फरीदाबाद",
    "Ulhasnagar": "उल्हासनगर",
    "Jamnagar": "जामनगर",
    "Srinagar": "श्रीनगर",
    "Guntur": "गुंटूर",
    "Sangli": "सांगली",
    "Vishakhapatnam (or) Vizag": "विशाखापत्तनम (या) विजाग",
    "Agra": "आगरा",
    "Tiruppur": "तिरुपूर",
    "Rajkot": "राजकोट",
    "Rajahmundry": "राजमुंदरी",
    "Shahjanpur": "शाहजहांपुर",
    "Bijapur (or) Vijayapura": "बीजापुर (या) विजयपुरा",
    "Jhansi": "झाँसी",
    "Patiāla": "पटियाला",
    "Mango": "मानगो",
    "Rajapalaiyam":"राजपलायम",
    "Kolhapur":"कोल्हापुर",
    "Sikar":"सीकर",
    "Kamarhati":"कमरहटी",
    "Tumkur":"तुमकुर",
    "Kagaznagar":"कागजनगर",
    "Karimnagar":"करीमनगर",
    "Solapur":"सोलापुर",
    "Asansol":"आसनसोल",
    "Panihati":"पनिहती",
    "Barasat":"बरसात",
    "Latur":"लातूर",
    "Bhatpara":"भतपारा",
    "Aizawl":"आइजोल",
    "Etawah":"इटावा",
    "Guwahati":"गुवाहाटी",
    "Handwara":"हंदवाड़ा",

  }

  hindiMissingKeyId = 0;
  missingKey: any = [];


}
