import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TeluguService {

  constructor() { }
  langs: any = {
    "Say Hii – Connect to someone around you. Keep your privacy. Spaark moves with you.": "హాయ్‌ చెప్పండి –  మీ పరిసరాల్లోని వారితో సంధానం కండి. మీ గోప్యతను నిలబెట్టుకోండి. స్పార్క్ మీతోనే కదులుతుంది.",
    "Services & Goods – Be a Seller or a Buyer. Make your market yourself. Build your profile. You may choose to keep the Spaark to move with you. It can be static also.": "వస్తువులు – సేవలు: విక్రేత లేదా కొనుగోలుదారు కండి. మీ సొంత మార్కెట్‌ను మీరే నిర్మించుకోండి. మీ ప్రాచుర్యం విస్తరించుకోండి. స్పార్క్ మీ వెంటే ఉండేలా లేదా స్థిరంగా ఒకేచోట ఉండేలా మీరు ఎంచుకోవచ్చు.",
    "Events & Announcements – Announce many things in your locality and let neighborhood know or join you. Spaark stays where you post it.": "కార్యక్రమాలు – ప్రకటనలు: మీ ప్రాంతంలోని అనేక  విషయాలను పొరుగువారికి తెలపండి. వారిని మీతో చేర్చుకోండి. మీ స్పార్క్‌ పోస్ట్ చేసిన చోటనే స్థిరంగా ఉంటుంది.", "Find anyone or anything – Post all your ‘to find’ queries here and let people around you help you find it.  Spaark moves with you.": "ఎవరినైనా/దేన్నయినా కనుగొనండి – మీ ‘అన్వేషణ’ సందేహాలన్నిటినీ ఇక్కడ పోస్ట్ చేయండి. దానిని వెదకడంలో  మీ పరిసరాల్లోని వారు మీకు సాయపడవచ్చు. స్పార్క్ మీతోనే కదులుతుంది.", "Community Feed – Connect with your neighborhood for any purpose. Share your photos, videos, or messages. Spaark stays where you post it.": "సమూహ సమాచారం: ఏ అవసరం కోసమైనా పొరుగువారితో సంధానం కండి. మీ ఫొటోలు, వీడియోలు లేదా సందేశాలను పంచుకోండి. స్పార్క్‌ మీరు  పోస్ట్ చేసిన చోటనే స్థిరంగా ఉంటుంది.", "Lost & Found – Inform your neighborhood when you lose or find something. Someonemay help you or you may help someone in finding their valuables. Spaark stays where it is posted.": "పోగొట్టుకున్నవి/దొరికినవి: మీరేదైనా పోగొట్టుకున్నా లేదా మీకు ఏదైనా దొరికినా మీ పొరుగువారికి తెలపండి. మీరు ఎవరికైనా/మీకు ఎవరైనా సహాయం చేయవచ్చు స్పార్క్ మీరు  పోస్ట్ చేసిన చోటనే స్థిరంగా ఉంటుంది.", "I Feel Unsafe – Use it when you want to alert people around, about your suspicions or your unsafe feeling of a certain place or environment. Seek or offer help in unsafe situations. Spaark moves with you.": "సురక్షితం కాదని మీరు సందేహించినా, భయమనిపించినా మీ పరిసరాల్లోని వారిని అప్రమత్తం చేయాలని భావిస్తే దీన్ని వాడండి. అభద్రత పరిస్థితులలో సహాయం కోరండి లేదా చేయండి. స్పార్క్ మీతోనే కదులుతుంది.", "Health Emergency –Use this feature to seek or to offer help, support, or queries related to health situations from people around you. Spaark moves with you.": "అత్యవసర ఆరోగ్య పరిస్థితి: ఆరోగ్య సంబంధిత సందేహ నివృత్తి,   సహాయం కోరడం లేదా చేయడం వంటివాటి కోసం స్పార్క్ లోని ఈ విశేషతను వాడుకోండి. స్పార్క్ మీతోనే కదులుతుంది.", "New Spaark": "కొత్త స్పార్క్",
    "characters remaining": "మిగిలిన అక్షరాలు",
    "Add images": "చిత్రాలను జోడించండి",
    "Active Packages": "యాక్టివ్  ప్యాకేజీలు",
    "Add Package": "ప్యాకేజీని జోడించండి",
    "Spaark Posting Details": "స్పార్క్ పోస్టింగ్ వివరాలు",
    "Your Spaark will be visible for": "మీ స్పార్క్ సమయ పరిమితి",
    "Your Spaark reach will be for": "మీ స్పార్క్ విస్తరణ పరిధి...", "Explore around": "మీ పరిసరాల్లో అన్వేషించండి",
    "Share": "పంచుకోండి",
    "Email": "ఈమెయిల్",
    "Comments": "వ్యాఖ్యలు", "Report": "ఫిర్యాదు", "Block": "నిషేధించు", "Replies": "జవాబులు", "Users": "వాడకందారులు", "Directions": "దిశ", "Call": "కాల్‌", "Chat": "చాట్", "chat": "చాట్", "No posts yet": "ఇప్పటికి పోస్టులేవీ లేవు", "Ratings": "రేటింగ్స్", "Total": "మొత్తం", "Days": "రోజులు", "days": "రోజులు", "Km": "కిలోమీటరు", "Rs": "రూపాయలు", "Post": "పోస్ట్", "Chats": "చాట్", "Contacts": "సంప్రదింపు నంబర్లు", "Requests": "అభ్యర్థనలు", "As": "(పేరుతో)", "As Anonymous": "అజ్ఞాత చాట్‌లు", "Contacts with Name": "పేరుతోగల నంబర్లు", "Contacts as Anonymous": "అజ్ఞాత నంబర్లు", 
    "Photo": "ఫొటో", 
    "Video": "వీడియో", 
    "File": "ఫైల్", 
    "Audio": "ఆడియో", "Chat cannot be replied anymore.": "చాట్‌కు ఇక జవాబివ్వబడదు", "Chat has been exited.": "చాట్ నుంచి నిష్క్రమణ", "Click to send Message": "సందేశం పంపేందుకు క్లిక్ చేయండి", "You have resumed chat.": "మీరు తిరిగి చాట్‌ను ప్రారంభించారు.",
    "Exit chat": "చాట్ నుంచి నిష్క్రమించండి",
    "Clear chat": "చాట్‌ను తొలగించు",
    "Block User": "వాడకందారును నిషేధించు",
    "Edit Name": "పేరును సవరించు",
    "Forward To": "ఫార్వర్డ్ చెయ్యి", "Chat Ended ": "చాట్ ముగిసింది", "Resume": "తిరిగి ప్రారంభించండి",
    "You cannot reply to this chat": "ఈ చాట్‌కు మీరు బదులివ్వలేరు", "Max 10 files can be uploaded": "గరిష్ఠంగా 10 ఫైళ్లు అప్‌లోడ్‌ చేయవచ్చు.", "you cant upload more than 4 media files": "గరిష్ఠంగా 4 ఫైళ్లు అప్‌లోడ్‌ చేయవచ్చు.", "You cant upload more than 2 images": "గరిష్ఠంగా 2 ఫొటోలు అప్‌లోడ్‌ చేయవచ్చు.", "Your location": "మీ ప్రదేశం", "Payment": "చెల్లింపు", "Day(s)": "రోజు(లు)", "km": "కిలోమీటరు", "m": "మీటరు", "Kms": "కిలో మీటర్లు", "Paid on": "చెల్లింపు తేదీ", "ago": "కిందట", "days ago ": "-", "mtr": "-", "day": "రోజులు", "hrs ago": "గంటల కిందట", "You do not have Contacts.": "మీకు ఏ నంబర్లూ లేవు", "You do not have any items in": "...లో మీ అంశాలేవీ లేవు",
    "Active": "క్రియాశీలం",
    "View": "గోచరత",
    "Repost": "రీపోస్ట్",
    "Rating": "రేటింగ్",
    "Seller": "విక్రేత",
    "You do not have any active Spaarks as Seller.": "విక్రేతగా మీకు క్రియాశీల స్పార్క్‌ లేవీ లేవు", "Manage Categories": "విభాగాలను నిర్వహించు", "You can only choose 4 categories to be active at a time": "మీరు ఒకేసారి 4 విభాగాలను మాత్రమే క్రియాశీలం చేయగలరు", "You can deactivate a service or replace with a new one after the specified time of the service is completed": "ఎంచుకున్న విభాగం నిర్దేశిత వ్యవధి ముగిస్తేనే మీరు దాన్ని నిష్క్రియం చేయగలరు.", "You can view or repost your earlier and current Spaarks. ": "మీరు మీ మునుపటి/ ప్రస్తుత స్పార్క్‌ లను చూడవచ్చు లేదా రీపోస్ట్ చేయవచ్చు", "You can view your earlier and current Spaarks": "మీరు మీ మునుపటి/ ప్రస్తుత స్పార్క్‌ లను చూడవచ్చు", "Live": "క్రియాశీలం", "Reposted on": "న రీపోస్ట్ చేయబడింది", "more repost(s)": "మరిన్ని రీపోస్ట్‌ (లు)", "Reposted": "రీపోస్ట్ చేయబడింది", "more times": "మరిన్ని సార్లు", "(Your Spaark will move with your current location.)": "మీ ప్రస్తుత ప్రదేశంతో మీ స్పార్క్ కదులుతుంది", "Add problem related images...": "సమస్య సంబంధిత చిత్రాలు జోడించండి", "Max size of images is 5MB": "చిత్రాల గరిష్ఠ పరిమాణం 5ఎంబీ", "You can see your conversation here": "మీరు మీ సంభాషణను ఇక్కడ చూడవచ్చు", "Admin has closed this ticket": "అడ్మిన్ ఈ టికెట్‌ను మూసివేశారు",
    "Submit": "సబ్మిట్",
    "SUBMIT": "సబ్మిట్",
    "Gender": "లింగం", "E-mail": "ఈమెయిల్", "Username": "వినియోగ నామం", "Phone": "ఫోన్", "Language": "భాష", "Telugu": "తెలుగు", "Unblock": "నిషేధం తొలగించు", "No Blocked Users.": "నిషేధిత వాడకందారులు లేరు", "Sorry to see you go. We will miss you.": "మీ నిష్క్రమణ విచారకరం. మిమ్మల్ని మరువలేం", "Look forward to have you return with same credentials, after 28 days.": "28 రోజుల తర్వాత ఇదే వివరాలతో మీరు తిరిగి రాగలరని ఆశిస్తున్నాం.", "Help us improve": "మెరుగుపడే దిశగా మాకు తోడ్పడండి", "I was spending more time on it": "నేను దానిపై అధిక సమయం వెచ్చిస్తున్నాను", "Too much of privacy": "మితిమీరిన గోప్యత", "Too little of privacy": "గోప్యత మరీ స్వల్పం", "Didn't find it useful": "ఇది ఉపయోగకరం కాదు", "Too many choices": "మితిమీరిన ఎంపికలు", "Complex layout": "సంక్లిష్ట స్వరూపం", "I have created another account": "నేను మరో ఖాతా సృష్టించాను", "Irrelevant inputs from other users": "ఇతర వాడకందారుల నుంచి అసంగత వివరాలు", "Less users around me": "నా పరిధిలో వాడకందారులు స్వల్పం", "Technical Issues": "సాంకేతిక సమస్యలు", "Comments if any": "వ్యాఖ్యలేవైనా...", "Delete": "తొలగించు", "Enter Text": "వచనాన్ని నింపండి.", "Features": "విశేషతలు", "FAQs": "తరచుగా అడిగే ప్రశ్నలు", "FAQ": "తరచుగా అడిగే ప్రశ్నలు", "Tap QR Code icon on the mobile app home screen": "మొబైల్ యాప్ హోమ్ స్క్రీన్‌లో క్యూఆర్ కోడ్ చిహ్నాన్ని నొక్కండి", "Live Spaark(s)": "క్రియాశీల స్పార్క్ లు", "Change": "మార్చు", "All Categories": "అన్ని విభాగాలు", "No more Spaarks": "ఇక స్పార్కులేవీ లేవు", "Longer distance and more time": "ఎక్కువ దూరం – అధిక సమయం", "You can see more Spaarks for more time.": "మీరు మరింతసేపు మరిన్ని స్పార్క్లను చూడవచ్చు.", "More people can see your Spaark for more time.": "మీ స్పార్క్ను మరింత మంది ఎక్కువ సమయం చూడవచ్చు", "Your Spaark will remain for longer time.": "మీ స్పార్క్ మరింతసేపు కొనసాగుతుంది.", "FREE": "ఉచితం", "Please select a category to create a Spaark": "స్పార్క్ సృష్టించడానికి దయచేసి ఒక విభాగాన్ని ఎంచుకోండి", "Spaarks posted as Seller": "విక్రేతగా పోస్ట్ చేసిన స్పార్క్స్", "Add New Spaark": "కొత్త స్పార్క్ జోడించండి", "Spaarks posted as Buyer": "కొనుగోలుదారుగా పోస్ట్ చేసిన స్పార్క్స్", "You will see users around your previous location when you view your earlier Spaark. You can see users around your current location by clicking on your current location icon.": "మీ మునుపటి స్పార్క్‌ ను చూస్తే ఆ ప్రదేశం చుట్టూగల వాడకందారులు కనిపిస్తారు. అలాగే మీ   ప్రస్తుత ప్రదేశాన్ని క్లిక్‌ చేస్తే దానిచుట్టూగల  వాడకందారులు కనిపిస్తారు.", "white space": "ఖాళీ స్థలం", "Lost Something": "ఏదైనా పోగొట్టుకున్నారా", "Found Something": "ఏదైనా దొరికిందా", "Lost": "పోగొట్టుకున్న", "Description cannot contain only whitespaces": "వివరణ స్థలం ఖాళీగా ఉండకూడదు",
    "Copied to clipboard": "క్లిప్బోర్డ్కు కాపీ చేయబడింది",
    "You already have a Spaark in this Service Category.": "ఈ సేవా విభాగంలో  మీకిప్పటికే స్పార్క్ ఉంది.",
    "Payment Processing": "చెల్లింపు ప్రక్రియ కొనసాగుతోంది",
    "Something went wrong.": "ఏదో  సమస్య తలెత్తింది",
    "Something Went Wrong.": "ఏదో  సమస్య తలెత్తింది",
    "You have reported a Content. Your details will remain confidential.": "మీరు సారాంశంపై ఫిర్యాదు చేశారు. మీ వివరాలు గోప్యంగా ఉంటాయి", "You have already reported to this post": "మీరిప్పటికే ఈ పోస్ట్‌ పై  ఫిర్యాదు చేశారు.", "Blocked user successfully.": "వాడకందారుపై నిషేధం సఫలం", "This Feature is available for mobiles only": "ఈ విశేషత మొబైల్స్‌కే లభ్యం", "Maximum 4 media files can be added": "గరిష్ఠంగా 4 మీడియా ఫైళ్ళను జోడించవచ్చు", "Either description or any one of alert is mandatory": "వివరణ లేదా ఏదైనా హెచ్చరిక తప్పనిసరి", "Category cannot contain only whitespaces": "విభాగం స్థలం ఖాళీగా ఉండకూడదు", "Account deleted successfully.": "ఖాతా తొలగింపు సఫలం", "This feature is only available in mobile app": "ఈ విశేషత మొబైల్‌ యాప్‌లోనే లభ్యం", "You have Reported a Content. Your details will remain confidential.": "మీరు సారాంశంపై ఫిర్యాదు చేశారు. మీ వివరాలు గోప్యంగా ఉంటాయి.",
    "Request Removed. ": "అభ్యర్థన తొలగించబడింది.",
    "You have already reported this Content.":"మీరు ఇప్పటికే ఈ కంటెంట్‌ని నివేదించారు.",
    "Request has been deleted": "అభ్యర్థన తొలగించబడింది.",
    "Request is Declined": "అభ్యర్థన తిరస్కరించబడింది",
    "Request is Accepted": "అభ్యర్థన ఆమోదించబడింది.",
    "Request has been Accepted": "అభ్యర్థన ఆమోదించబడింది.",
    "Profile Picture updated successfully.": "ప్రొఫైల్ చిత్రం మార్పు సఫలం",
    "Ticket created. View it in My Tickets.": "టికెట్ సృష్టించబడింది. దీన్ని “నా టికెట్లు”లో చూడండి",
    "Ticket Created": "టికెట్ సృష్టించబడింది",
    "You cannot send empty message.": "సందేశం ఖాళీగా పంపే వీల్లేదు",
    "User Unblocked.": "వాడకందారుపై నిషేధం తొలగించబడింది.",
    "Have anything to help? Write here": "సహాయం చేయగలరా? ఇక్కడ రాయండి.",
    "Ask anything here": "ఇక్కడ ఏదైనా అడగండి",
    "Type here": "ఇక్కడ టైప్‌ చేయండి",
    "Siren": "సైరన్", "Red Flash": "ఎర్ర లైటు ",
    "SMS Family": "కుటుంబానికి సందేశం పంపించు",
    "Lonely/Isolated Place": "నిర్జన/నిర్మానుష్య ప్రదేశం",
    "Unsafe Crowd": "అల్లరిమూక",
    "Animal Attack": "జంతు దాడి",
    "Write details of the unsafe situation around": "భద్రతలేని పరిసర పరిస్థితుల వివరాలివ్వండి",
    "Eve-Teasing": "స్త్రీలపై  వేధింపులు",
    "Unmanaged Traffic": "అనియంత్రిత రాకపోకలు",
    "Moving Spaarks": "కదిలే స్పార్క్స్",
    "Spaark Location Visibility": "స్పార్క్ ప్రదేశం గోచరత ", "Write details of what you have lost or found. Pictures help.": "మీరు పోగొట్టుకున్న లేదా దొరికినవాటి వివరాలు రాయండి. చిత్రాలు ఉపయోగకరం", "Material": "సామగ్రి", "Pet": "పెంపుడు జంతువు", "Human": "మానవ", "Other": "ఇతరాలు", "Write details of what you are looking for.": "మీకు ఏది అవసరమో ఆ వివరాలివ్వండి.", "Write anything good": "మంచిది ఏదైనా రాయండి", "Write for the person you seek to connect with. Pictures help.": "మీరు సంధానం కాదలచిన వ్యక్తి కోసం/ గురించి రాయండి. చిత్రాలు ఉపయోగకరం.", "No more items": "ఎలాంటి అంశాలూ లేవు", "Spaarks Team": "స్పార్క్స్ బృందం", "has requested to chat with you": "...మీతో చాట్‌ కోసం  అభ్యర్ధించారు", "Today": "ఈ రోజు", "Lonely/Isolated": "నిర్జన/నిర్మానుష్య ప్రదేశం",
    "Giving details of the event will help users know and join. Pictures help.": "కార్యక్రమ వివరాలిస్తే  వాడకందారులు తెలుసుకుని, పాల్గొంటారు. చిత్రాలు ఉపయోగకరం.", "Write details of the help needed or offered.": "మీరు చేయగల లేదా కావాల్సిన సహాయం వివరాలివ్వండి..", "Alert Around": "అంతటా అప్రమత్తత", "Please select one of the below": "దయచేసి దిగువనున్న వాటిలో ఒకటి ఎంచుకోండి.", "Enter your message": "మీ సందేశాన్ని నింపండి", "Connect as": ".... గా సంధానం కండి", "Show More": "మరింత చూపు", "Show Less": "తక్కువ చూపించు", "Say Hii": "హాయ్! చెప్పండి", "Services & Goods": "వస్తువులు - సేవలు", "Spaarks Home": "స్పార్క్స్ హోమ్", "I Feel Unsafe": "నాకు భయంగా ఉంది",
    "Events & Announcements": "కార్యక్రమాలు- ప్రకటనలు", "Community Feed": "సమూహ సమాచారం", "Find Anyone or Anything": "ఎవరినైనా లేదా దేనినైనా  కనుగొనండి", "Health Emergency": "అత్యవసర ఆరోగ్య పరిస్థితి", "Scan the QR code to continue using Spaarks Web": "స్పార్క్స్ వెబ్ వాడకం కొనసాగించేందుకు QR కోడ్ను స్కాన్ చేయండి", "Open Spaarks application on your mobile phone": "మీ మొబైల్ ఫోన్లో స్పార్క్స్ అనువర్తనం  తెరవండి", "Tap QR Code icon": "QR కోడ్ చిహ్నాన్ని నొక్కండి", "the app home screen.": "యాప్ హోమ్ స్క్రీన్", "Point your mobile phone towards the screen to scan the QR Code.": "క్యూ ఆర్ (QR) కోడ్ స్కానింగ్‌ కోసం మొబైల్ ఫోన్ను స్క్రీన్ వైపు చూపండి", "Buyer": "కొనుగోలుదారు", "My Spaarks": "నా స్పార్క్స్", "My Info": "నా స్పార్క్స్", "My Chats": "నా చాట్లు", "Emergency Contacts": "అత్యవసర నంబర్లు", "App Tour": "అనువర్తన సందర్శన", "Payments": "చెల్లింపులు", "Help": "సహాయం", "Terms & Policies": "నిబంధనలు/విధానాలు", "Settings": "సెట్టింగులు", "Logout": "నిష్క్రమణ", "Payment was successful": "చెల్లింపు సఫలం", "Payment was cancelled": "చెల్లింపు రద్దయింది.", "Note: These Posts are as per your visibility radius. Enter a feature to see more posts.": "గమనిక: ఈ పోస్టులు మీరు ఎంపిక చేసుకున్న గోచరత పరిధిలోనివి. మరిన్ని పోస్టులు చూడటానికి ఏదైనా విశేషతలోకి వెళ్లండి", "You can view your earlier and current Spaarks.": "మీరు మీ మునుపటి/ ప్రస్తుత స్పార్క్లను చూడవచ్చు.", "You can view or repost your earlier and current Spaarks.": "మీరు మీ మునుపటి/ ప్రస్తుత స్పార్క్‌ లను చూడవచ్చు లేదా రీపోస్ట్ చేయవచ్చు", "Write here.": "ఇక్కడ రాయండి", "Invoice will be generated with your billing details as below": "బిల్లు సమాచారం ప్రకారం  మీ లావాదేవీ పత్రం సిద్ధమవుతుంది", "Billing Information": "బిల్లు సమాచారం", "Country": "దేశం", "Cancel Payment": "చెల్లింపు రద్దు చెయ్యి", "Continue Payment": "చెల్లింపు కొనసాగించు",
    "Save": "సేవ్ చెయ్యి", "Show Less…": "తక్కువ చూపించు", "remaining": "మిగిలినవి", "mins": "నిమిషాలు", "I have lost": "నేను పోగొట్టుకున్నాను", "I have found": "నాకు దొరికింది", "Rung a Siren": "సైరన్ మోగించు", "Red Flashed": "ఎర్ర లైటు వెలిగింది", "Alerted Around": "అంతటా అప్రమత్తం చేయబడింది", "Sent SMS to family": "కుటుంబానికి సందేశం పంపబడింది", "Remove Request": "అభ్యర్థనను తొలగించు", "LOADING...": "లోడ్‌ అవుతోంది.", "times": "దఫాలు", "Edit your posting preference(optional)": "మీ పోస్టింగ్ ప్రాధాన్యాన్ని సవరించండి (ఐచ్ఛికం)", "Fixed till": "... వరకు పరిష్కరించబడింది", "Original Submission On": "వాస్తవ సమర్పణ తేదీ", "Moving Spaark moves with you. Your phone's location is refreshed at some intervals, hence your Spaark’s location is also refreshed. The users at the latest location will now be able to see your Spaark in the specified radius.": "-మీ స్పార్క్ మీతోపాటు కదులుతుంది. మీ ఫోన్లోని ప్రదేశ సూచీ తరచూ మారుతూంటుంది. కాబట్టి మీ స్పార్క్ ప్రదేశం కూడా మారుతుంది. తద్వారా కొత్త ప్రదేశంలో వాడకందారులు మీ స్పార్క్ను నిర్దిష్ట పరిధిలో చూడగలరు.", "Static Spaark stays where you post it and does not move with you. Location of your Spaark is not refreshed even if you move. You will be able to see users of the new location if you move but your Spaark will be left at your earlier location and will be visible to the users who would cross your earlier location only.": "స్థిరమైన స్పార్క్ మీరు పోస్ట్ చేసిన చోటనే ఉంటుంది తప్ప మీతో కదలదు. మీరు కదిలినా మీ స్పార్క్ మునుపటి స్థానంలోనే ఉంటుంది.  మీ స్థానం మారితే మీరు కొత్త ప్రదేశంలోని వాడకందారులను చూడగలరు. కానీ, మీ స్పార్క్ మునుపటి ప్రదేశంలోనే ఉంటుంది కాబట్టి ఆ ప్రదేశాన్ని దాటేవారికి మాత్రమే మీ స్పార్క్  కనిపిస్తుంది.", "Select Any": "ఏదైనా ఎంచుకోండి", "Enable Any": "దేనినైనా క్రియాశీలం చేయండి", "You can't reply to this chat": "మీరు ఈ చాట్‌కు బదులివ్వలేరు", "You don’t have Spaarks in": "మీకు... స్పార్క్లు లేవు",
    "Spaarks": "స్పార్క్స్",
    "SPAARKS": "స్పార్క్స్",
    "You do not have any ratings in": "మీకు.. ఎలాంటి రేటింగులు లేవు",
    "You can request for an invoice of the payment transaction to your registered mail directly": "చెల్లింపు/లావాదేవీ పత్రాన్ని నేరుగా మీ నమోదిత పంపాలని అభ్యర్థించవచ్చు.", "These posts are as per your visibility radius. Enter a feature to see more posts.": "ఈ పోస్టులు మీరు ఎంపిక చేసుకున్న గోచరత పరిధిలోనివి. మరిన్ని పోస్టులు చూడటానికి ఏదైనా విశేషతలోకి వెళ్లండి.", "You do not have any notifications at present": "మీకు ప్రస్తుతం సూచనాత్మక ప్రకటనలేవీ లేవు", "Notifications": "సూచనాత్మక ప్రకటనలు",
    "Chat request": "చాట్ రిక్వెస్ట్", "Anonymous": "అజ్ఞాత", "ACCEPT": "ఆమోదించు", "IGNORE": "విస్మరించు", "Reports": "ఫిర్యాదులు", "Rate your experience with service provider": "సేవా ప్రదాతతో మీ అనుభవాన్ని రేట్ చేయండి", "Write about your experience with the Seller": "విక్రేతతో మీ అనుభవం గురించి రాయండి", "User(s) have reported this": "వాడకందారు(లు)దీనిపై ఫిర్యాదు చేశారు.", "My Account": "నా ఖాతా", "Company Details": "కంపెనీ వివరాలు", "Blocked Users": "నిషేధిత వాడకందారులు", "Delete Account": "ఖాతాను తొలగించు", "Spaark Reports": "స్పార్క్ ఫిర్యాదులు", "Your reviews help Sellers build their profile. Type something good here": "మీ సమీక్షలు విక్రేత ప్రొఫైల్ మెరుగుకు తోడ్పడతాయి. మీకు నచ్చినవి రాయండి", "Please rate your service provided in": "దయచేసి ....లో మీకందిన సేవను రేట్ చేయండి", "My Tickets": "నా టికెట్లు", "Subscriptions": "సభ్యత్వలు", "You have not subscribed to any Seller yet.": "మీరు ఇంకా ఏ విక్రేతకు సభ్యత్వాన్ని పొందలేదు.", "Unsubscribe": "సభ్యత్వాన్ని తొలగించండి", "Subscribe": "సభ్యత్వాన్ని పొందండి", "You will be notified whenever these Sellers come within 500 mts of your location.": "విక్రేత మీ స్థానానికి 500 మీటర్ల దూరంలో ఉన్నప్పుడు మీకు తెలియజేయబడుతుంది.",
    "Are you sure you want to block this user?": "మీరు ఖచ్చితంగా ఈ వ్యక్తిని నిరోధించాలనుకుంటున్నారా?",
    "Delete Alert : Are you sure, you want to delete this post?": "తొలగించండి హెచ్చరిక: మీరు ఖచ్చితంగా, మీరు ఈ పోస్ట్ను తొలగించాలనుకుంటున్నారా?", "selectOneFromSix : please select atleast one of the above six options.": "దయచేసి పై ఆరు ఎంపికలలో కనీసం ఒకదాన్ని ఎంచుకోండి.", "Completed": "పూర్తయింది",
    "Are you sure, you want to delete this spaark?":"మీరు ఖచ్చితంగా, ఈ స్పార్క్‌ను తొలగించాలనుకుంటున్నారా?",
    "Ignored": "విస్మరించబడింది",
    "No reviews yet": "ఇంకా సమీక్షలు లేవు",
    "Categories": "విభాగాలు",
    "Sub-categories": "ఉప – విభాగాలు",
    "Small Scale Entrepreneurs": "చిన్నతరహా పారిశ్రామికవేత్తలు",
    "Tailor/Boutique": "టైలర్/బొటీక్",
    "Handicrafts": "హస్తకళలు", "Jewellery Making": "ఆభరణాల తయారీ",
    "Food and related": "ఆహారం - తత్సంబంధిత ",
    "Bakery": "బేకరీ",
    "Catering": "కేటరింగ్",
    "Fruits/Vegetables Seller": "పండ్లు/కూరగాయల విక్రేత",
    "Gol-gappe/Chaat": "పానీపూరీ/చాట్",
    "Juice Corner": "పండ్లరసాల దుకాణం",
    "Tapri/Panwala/Tea-stall": "కిరాణా/పాన్/టీ దుకాణం",
    "Home Based Food & Products/Tiffin": "ఇంటి ఆహారం-ఉత్పత్తులు/టిఫిన్",
    "Workers/Helpers": "కార్మికులు/సహాయకులు",
    "Driver/Car-Washer": "డ్రైవర్/కారు కడిగేవారు",
    "Maid/Cook": "పనిమనిషి/వంటమనిషి",
    "Miscellaneous Helper- Female": "ఇతరత్రా పనుల్లో సహాయకులు – మహిళ",
    "Miscellaneous Helper- Male": "ఇతరత్రా పనుల్లో సహాయకులు - పురుష",
    "Office Assistant": "కార్యాలయ సహాయకుడు",
    "Security/ Guard Service": "భద్రత/కాపలా సేవ ",
    "Unskilled/Daily Wage Labour": "నైపుణ్యం లేని/దినవేతన కార్మికులు",
    "Waiters/Bearers": "వెయిటర్లు/బేరర్లు",
    "Care and Paramedic": "సంరక్షణ – అర్థవైద్య సేవలు ",
    "Baby Sitter/Pet Sitter": "బాలల సంరక్షకులు/పెంపుడు జంతు సంరక్షకులు",
    "Post Delivery Care-taker": "చేరవేత అనంతర పర్యవేక్షకుడు",
    "Nurse and Paramedic": "నర్సు – అర్థవైద్య సిబ్బంది",
    "Pharmacy/Medical Supplies": "ఫార్మసీ/ఔషధ సరఫరాలు",
    "Physiotherapist": "శరీర వ్యాయామ నిపుణులు",
    "Vet": "పశువైద్యుడు",
    "Organic Produce": "సేంద్రియ ఉత్పత్తి",
    "Farm Produce": "వ్యవసాయ ఉత్పత్తి",
    "Grains/Pulses": "ధాన్యాలు/పప్పులు",
    "Fruits/Vegetables": "పండ్లు/కూరగాయలు",
    "Milk and milk products": "పాలు - పాల ఉత్పత్తులు",
    "Flowers": "పూలు",
    "Poultry/Meat/Fish": "కోడి/మాంసం/చేప",
    "Spices/Herbs": "సుగంధ ద్రవ్యాలు/మూలికలు",
    "Exotic products": "విదేశీ ఉత్పత్తులు",
    "Stores": "దుకాణాలు",
    "Dhabas": "ధాబాలు",
    "General Store": "సాధారణ దుకాణాలు",
    "Small Eating Joints": "చిన్న ఆహార దుకాణాలు",
    "Sweet Shops": "స్వీట్ల దుకాణాలు",
    "Resell or Give away": "మారు విక్రయం లేదా ఇచ్చి వేయడం",
    "Appliances/Furniture": "ఉపకరణాలు/ఫర్నీచర్",
    "Books": "పుస్తకాలు",
    "Car/Bike": "కారు/బైక్",
    "Children’s Toys/related": "పిల్లల బొమ్మలు/తత్సంబంధిత",
    "Food/Clothes/Utensils": "ఆహారం/దుస్తులు/పాత్రలు",
    "IT & Hardware": "ఐటీ - హార్డ్వేర్",
    "Others/Miscellaneous": "ఇతరాలు/చిల్లరమల్లర ",
    "Beauty and Fitness": "సౌందర్యం -దృఢత్వం",
    "Dietician/Nutritionist": "ఆహార శాస్త్రవేత్త/పౌష్టికాహార నిపుణుడు",
    "Fitness/Yoga": "దృఢత్వం/యోగా",
    "Home Service Beautician": "ఇంటివద్ద సౌందర్య సేవ",
    "Masseurs/Massage": "మాలీష్ నిపుణులు/మాలీష్‌",
    "Parlour/Hairdressers": "పార్లర్/కేశాలంకరణ నిపుణులు",
    "Stylist/Makeup/Fashion Tutor": "స్టైలిస్ట్/మేకప్/ఫ్యాషన్ బోధకులు",
    "Freelancers/Coaches/Tutors": "స్వతంత్ర నిపుణులు/శిక్షకులు/బోధకులు",
    "Content Writers": "సారాంశ రచయితలు",
    "Cooking Classes": "వంటల తరగతులు",
    "Digital Marketing Expert": "డిజిటల్ మార్కెటింగ్ నిపుణుడు",
    "Lifestyle Coach": "జీవనశైలి శిక్షకులు",
    "Music Troops": "సంగీత బృందాలు",
    "Music/Dance Tutor": "సంగీతం/నృత్య బోధకులు",
    "Performing Arts": "ప్రదర్శనాత్మక కళలు",
    "Photographer": "ఛాయాగ్రాహకుడు",
    "Sports Coach": "క్రీడా శిక్షకుడు",
    "Tutors": "బోధకులు",
    "Consultants": "సలహాదారులు",
    "CA/Tax Consultant": "సీఏ/పన్ను సలహాదారు",
    "Career Counsellor": "ఉపాధి సలహాదారు",
    "Event Planner/Wedding Consultant": "కార్యక్రమ ప్రణాళిక కర్త/వివాహ సలహాదారు",
    "Interior Designer": "గృహాలంకరణ నిపుణుడు",
    "Legal Consultant": "న్యాయ సలహాదారు",
    "Palmist/Astrologer/Tarot": "హస్త సాముద్రికుడు/జ్యోతిష్కుడు/టారో నిపుణుడు",
    "Routine Services": "సాధారణ సేవలు",
    "Bag & Related Repair": "బ్యాగులు, తత్సంబంధ మరమ్మతు",
    "Carpenter": "వడ్రంగి",
    "Cobbler": "చర్మకారులు",
    "Dhobi/Dry cleaner/Washer": "రజక/డ్రై క్లీనర్/దుస్తులు ఉతికేవారు",
    "Electrician and Appliances Repair": "విద్యుత్‌ - గృహోపకరణ మరమ్మతు",
    "Garbage Collector": "వ్యర్థాల సేకరణదారులు",
    "Gardener/Nursery": "తోటమాలి/మొక్కల పెంపకం",
    "Locksmith": "తాళాలు బాగుచేసేవారు",
    "Painter": "చిత్రకారుడు",
    "Plumber": "నీటిగొట్టాల పని నిపుణుడు",
    "Raddiwala": "చిత్తు కాగితాల కొనుగోలుదారు",
    "IT": "ఐటీ",
    "Animators/Developers/Coders": "యానిమేటర్లు/డెవలపర్లు/కోడర్లు",
    "Broadband/Internet": "బ్రాడ్బ్యాండ్/ఇంటర్నెట్",
    "Computer Training/related": "కంప్యూటర్ శిక్షణ/తత్సంబంధిత",
    "Computer/Mobile Repair": "కంప్యూటర్/మొబైల్ మరమ్మతు",
    "IT related Professionals": "ఐటీ సంబంధిత వృత్తి నిపుణులు",
    "IT Security": "ఐటీ భద్రత",
    "House on Rent": "అద్దెకు ఇల్లు",
    "Roommates/Flatmates": "గది సహచరులు/ఫ్లాట్ సహచరులు",
    "Domestic Items on Rent": "అద్దెకు గృహోపకరణాలు",
    "Tents/Beddings on Rent": "అద్దెకు గుడారాలు/పరుపులు",
    "Transport related": "రవాణా సంబంధితం",
    "Hire Vehicle": "అద్దె వాహనం",
    "Mechanic/Puncture Repair": "మెకానిక్/పంక్చర్ మరమ్మతులు",
    "Rickshaw/Autorickshaw": "రిక్షా/ఆటో రిక్షా",
    "Taxi- Sharing/Single": "టాక్సీ-షేరింగ్/సింగిల్",
    "Others": "ఇతరాలు",
    "Rate your experience with the Seller": "విక్రేతతో మీ అనుభవాన్ని రేట్ చేయండి",
    "Write about your experience with the service provider": "సేవా ప్రదాతతో మీ అనుభవం గురించి రాయండి",
    "No Subscribed Users": "సభ్యత్వం పొందిన వాడకందారులు లేరు",
    "Please select one option among six": "దయచేసి పై ఆరు ఎంపికలలో కనీసం ఒకదాన్ని ఎంచుకోండి.",
    "Are you sure  you want to Report?": "మీరు ఖచ్చితంగా, మీరు ఈ వ్యాఖ్యను ఫిర్యాదు చెయ్యాలనుకుంటున్నారా?",
    "GSTIN(Optional)": "జీఎస్‌టిన్‌ (ఐచ్ఛికం)",
    "Country(Optional)": "దేశం (ఐచ్ఛికం)",
    "Street Food": "వీధి పక్కన ఆహారం",
    "hrs": "గంటల",
    "say_hi_decription": "మీ పరిసరాల్లోని వ్యక్తులతో సాధారణంగా కనెక్ట్ అవ్వండి. మీ గోప్యతను ఉంచండి. స్పార్క్ మీతో కదులుతుంది.",
    "services_and_goods_description": "విక్రేత లేదా కొనుగోలుదారుగా ఉండండి. మీ మార్కెట్‌ను మీరే చేసుకోండి. మీ ప్రొఫైల్‌ను రూపొందించండి. మీరు స్పార్క్‌ను కదిలే లేదా స్థిరంగా ఉంచడానికి ఎంచుకోవచ్చు.",
    "i_feel_unsafe_description": "మీ అనుమానాలు లేదా ఒక నిర్దిష్ట స్థలం గురించి మీ భావన గురించి ప్రజలను అప్రమత్తం చేయాలనుకున్నప్పుడు దీన్ని ఉపయోగించండి. అసురక్షిత పరిస్థితులలో సహాయం చూడండి లేదా అందించండి.",
    "Note": "గమనిక",
    "events_and_announcements_description": "మీ ప్రాంతంలోని అనేక విషయాలను ప్రకటించండి మరియు మీతో చేరడానికి వ్యక్తులను అనుమతించండి. మీరు ఉంచిన చోట స్పార్క్ ఉంటుంది.",
    "community_feed_description": "ఏ విధమైన ప్రయోజనం కోసం అయినా మీ ప్రాంతంతో కనెక్ట్ అవ్వండి. మీ ఫోటోలు, వీడియోలు లేదా సందేశాలను భాగస్వామ్యం చేయండి.స్పార్క్ మీరు ఉంచిన చోట ఉంటుంది.",
    "find_anyone_or_anything_description": "మీ అన్ని అన్వేషణ ప్రశ్నలను ఇక్కడ ఉంచండి మరియు దాన్ని పరిష్కరించడంలో మీ చుట్టూ ఉన్న వ్యక్తులు మీకు సహాయపడండి. స్పార్క్ మీతో కదులుతుంది.",
    "lost_and_found_description": "మీరు ఏదైనా కోల్పోయినప్పుడు లేదా ఏదైనా కనుగొన్నప్పుడు మీ చుట్టూ తెలియజేయండి. ఎవరైనా మీకు సహాయం చేస్తారో లేదా వారి విలువైన వస్తువులను కనుగొనడంలో మీరు ఎవరికైనా సహాయం చేస్తారో మీకు తెలియదు. మీరు ఉంచిన చోట స్పార్క్ ఉంటుంది.",
    "health_emergency_description": "మీ చుట్టూ ఉన్న వ్యక్తుల నుండి ఆరోగ్యానికి సంబంధించిన సహాయం, మద్దతు లేదా ప్రశ్నలను వెతకడానికి లేదా అందించడానికి ఈ లక్షణాన్ని ఉపయోగించండి. స్పార్క్ మీతో కదులుతుంది.",
    "Male": "పురుషుడు", "Female": "స్త్రీ",
    "Please select country": "దయచేసి దేశాన్ని ఎంచుకోండి",
    "India": "భారతదేశం",
    "Address": "చిరునామా",
    "State": "రాష్ట్రం",
    "No Blocked Users": "నిరోధించిన వాడకందారులు లేరు",
    "Contact Us": "మమ్మల్ని సంప్రదించండి",
    "Payment related issues?": "చెల్లింపు సంబంధిత అంశాలు",
    "Are you seeking information?": "మీరు సమాచారం కోరుతున్నారా?",
    "Are you facing any problem with application?": "మీరు అనువర్తనంతో ఏదైనా సమస్యను ఎదుర్కొంటున్నారా?",
    "Tell us": "మాకు చెప్పండి",
    "Has your payment failed?": "మీ చెల్లింపు విఫలమైందా?",
    "Information is being seeked by user": "వాడకందారు సమాచారం కోరుతున్నారు",
    "Going to login page automatically": "స్వయంచాలకంగా లాగిన్ పేజీకి వెళుతోంది",
    "Payment failed": "చెల్లింపు విఫలం",
    "Payment successful": "చెల్లింపు సఫలం",
    "Initiated on": "ప్రారంభించిన తేదీ",
    "Say Hii Requests": "హాయ్‌! చెప్పండి అభ్యర్థన",
    "You do not have Contacts..": "మీకు నంబర్ల  లేవు.",
    "What people are saying...": "ప్రజలు ఏమి చెబుతున్నారు ...",
    "About me": "నా గురించి",
    "About service": "సేవ గురించి",
    "Spaarks Posted So Far": "ఇప్పటివరకు పోస్ట్ చేసిన స్పార్క్స్",
    "Seller Profile": "విక్రేత ప్రొఫైల్",
    "No comments yet": "ఇంకా వ్యాఖ్యలు లేవు",
    "Show More...": "ఇంకా చూపించు…",
    "Spaark Reporte": "స్పార్క్ నివేదించింది",
    "Comment": "వ్యాఖ్య",
    "Reviews": "సమీక్షలు",
    "around you.": "మీ చుట్టూ",
    "Your Spaark": "మీ స్పార్క్",
    "Review": "సమీక్ష",
    "Spaark": "స్పార్క్",
    "my_spaark_description": "మీరు మీ మునుపటి మరియు ప్రస్తుత స్పార్క్‌లను చూడవచ్చు",
    "my_spaark_desc_two": "మీరు మీ మునుపటి మరియు ప్రస్తుత స్పార్క్‌లను చూడవచ్చు లేదా రీపోస్ట్ చేయవచ్చు",
    "Static Spaarks": "స్థిరమైన స్పార్క్",
    "Static Spaark": "స్థిరమైన స్పార్క్",
    "Ticket ID": "టికెట్ ఐడి",
    "Created at": "సృష్టించిన తేదీ",
    "Enter your queries here": "మీ ప్రశ్నలను ఇక్కడ నమోదు చేయండి",
    "Closed": "మూసివేయబడింది",
    "Open": "తెరవండి",
    "Active Categories": "క్రియాశీల విభాగాలు",
    "Connect With Us": "మాతో సంధానం అవ్వండి",
    "Any Other": "మరేదైనా",
    "Requests sent":"పంపిన రిక్యూస్ట్స్",
    "Real Estate and Rentals": "స్థిరాస్తి, అద్దె ఇళ్ల లావాదేవీలు",
    "Watch Spaarks Tutorials": "స్పార్క్స్ ట్యుటోరియల్స్ చూడండి",
    "Subscribe us for many useful videos about Spaarks": "ఉపయోగకరమైన వీడియోల కోసం స్పార్క్స్  సభ్యత్వాన్ని పొందండి",
    "Tweet us on @Spaarks_Smiles": "మాకు @Spaarks_Smiles తో ట్వీట్ చేయండి",
    "Follow us for interesting updates": "ఆసక్తికరమైన నవీకరణల కోసం మమ్మల్ని అనుసరించండి",
    "Like us on Spaarks.Smiles": "Spaarks.Smiles లో మమల్ని లైక్ చేయండి",
    "Keep in touch with us for great posts": "గొప్ప పోస్ట్‌ల కోసం మాతో సన్నిహితంగా ఉండండి",
    "Tag us @Spaarks_Smiles": "@Spaarks_Smiles ట్యాగ్ చేయండి",
    "We keep pictures here for your everyday use": "మీ రోజువారీ ఉపయోగం కోసం మేము ఇక్కడ చిత్రాలను ఉంచుతాము",
    "Connect with us @Spaarks": "స్పార్క్స్ తో సంధానం అవ్వండి",
    "Be professionally linked. We keep our job postings here": "మేము మా ఉద్యోగ పోస్టింగ్‌లను ఇక్కడ ఉంచుతాము",
    "Delete for me": "నాకు మాత్రమే తొలగించు",
    "Delete for both": "ఇద్దరికీ తొలగించు",
    "This message has been deleted": "ఈ సందేశం తొలగించబడింది",
    "Copy text": "వచనాన్ని కాపీ చేయండి",
    "Forward": "ఫార్వర్డ్",
    "Type a message...": "సందేశం టైప్ చేయండి",
    "just now": "ఇప్పుడే",
    "Pay": "చెల్లించండి",
    "PAID": "చెల్లించారు",
    "OK": "అలాగే",
    "Reply": "ప్రత్యుత్తరం",
    "Deleted Succesfully": "విజయవంతంగా తొలగించబడింది", "Say Hi": "హాయ్! చెప్పండి",
    "Info reported successfully.": "మీరు స్పార్క్స్ పై ఫిర్యాదు చేశారు",
    "SOS! Help Needed": "ఎస్‌ఓఎస్ (SOS) సహాయం అవసరం",
    "Comment Reported": "వ్యాఖ్యపై ఫిర్యాదు వచ్చింది",
    "Are you sure you want to report?": "మీరు కచ్చితంగా ఫిర్యాదు చేయాలని భావిస్తున్నారా?",
    "Write about the service, quality, pricing required or offered": "మీకు అందే/మీరందించే వస్తువు లేదా సేవ నాణ్యత, ధర గురించి రాయండి.  చిత్రాలుంటే ఉపయోగకరం",
    "Message Forwarded Successfully": "సందేశం ఫార్వర్డ్ చేయబడింది",
    "Are you sure, you want to clear chat?": "మీరు ఖచ్చితంగా చాట్ క్లియర్ చేయాలనుకుంటున్నారా?",
    "New Comment": "క్రొత్త వ్యాఖ్య",
    "New Request in Say Hii": "హాయ్! చెప్పండి‌లో కొత్త అభ్యర్థన",
    "You have active web login": " మీకు క్రియాశీల వెబ్ లాగిన్ ఉంది",
    "Spaark Created Successfully": "స్పార్క్ విజయవంతంగా సృష్టించబడింది",
    "Your spaark will move with your current location.": "మీ ప్రస్తుత ప్రదేశంతో మీ స్పార్క్ కదులుతుంది",
    "No Ratings Yet": "ఇంకా రేటింగ్స్ లేవు",
    "Payment Succes": "చెల్లింపు సఫలం",
    "1) Users of Say Hii feature can send a ‘ Request ’ to connect with someone who posted a Say hii Spaark.": "1) హాయ్ చెప్పండి! విశేషత యొక్క వాడకందారులు హాయ్ చెప్పండి విశేషతలో స్పార్క్ పోస్ట్ చేసిన వారితో సంధానం అవ్వడానికి ‘అభ్యర్ధన’ పంపవచ్చు.",
    "2) Other Users cannot see this Request.": "2) ఇతర వాడకందారులు ఈ అభ్యర్థనను చూడలేరు.",
    "3) Users who posted the Say Hii Spaark can accept or Reject this Request.": "3) హాయ్! చెప్పండి విశేషతలో స్పార్క్ పోస్ట్ చేసిన వాడకందారులు ఈ అభ్యర్థనను అంగీకరించవచ్చు లేదా తిరస్కరించవచ్చు.",
    "4) If Request is accepted, Chat opens.": "4) అభ్యర్థన అంగీకరించబడితే, చాట్ తెరుచుకుంటుంది.",
    "5) If Request is rejected, the user sending the request does not know it.This is a privacy Feature. ": " ",
    "6) Chats are sorted and stored under Anonymous or Name.": "6) చాట్లు క్రమబద్ధీకరించబడతాయి మరియు అజ్ఞాత లేదా పేరు క్రింద నిల్వ చేయబడతాయి.",
    "Unmanaged Traff": "అనియంత్రిత రాకపోకలు",
    "Lonely/Isolated Plac": "నిర్జన/నిర్మానుష్య ప్రదేశం",
    "Pending": "పెండింగ్‌",
    "Selected": "ఎంచుకోబడింది", "hr(s)": "గంటల"
    , "01. Longer distance and more time": "ఎక్కువ దూరం – అధిక సమయం",
    "Connecting as": "...గా కనెక్ట్ అవుతోంది",
    "Connecting Anonymously": "అజ్ఞాతంగా కనెక్ట్ అవుతోంది",
    "Send Request": "అభ్యర్థన పంపండి",
    "Expertise": "నైపుణ్యం",
    "Services Pictures": "సేవల చిత్రాలు",
    "greet": "హాయ్! చెప్పండి",
    "market": "వస్తువులు - సేవలు",
    "unsafe": "నాకు భయంగా ఉంది",
    "showtime": "కార్యక్రమాలు- ప్రకటనలు",
    "playtime": "సమూహ సమాచారం",
    "people": "ఎవరినైనా లేదా దేనినైనా  కనుగొనండి",
    "ambulance": "అత్యవసర ఆరోగ్య పరిస్థితి",
    "deposit": "పోయినవి/దొరికినవి"
    , "Payment Successful": "చెల్లింపు సఫలం",
    "Please select state": "దయచేసి రాష్ట్రాన్ని ఎంచుకోండి",
    "Select your state": "రాష్ట్రాన్ని ఎంచుకోండి",
    "Select your country": "మీ దేశాన్ని ఎంచుకోండి"
    // States Name
    , "Andhra Pradesh": "ఆంధ్రప్రదేశ్",
    "Arunachal Pradesh": "అరుణాచల్ ప్రదేశ్",
    "Assam": "అస్సాం",
    "Bihar": "బీహార్",
    "Chhattisgarh": "చ్చత్తీస్గఢ్", "Goa": "గోవా",
    "Gujarat": "గుజరాత్",
    "Haryana": "హర్యానా",
    "Himachal Pradesh": "హిమాచల్ ప్రదేశ్",
    "Jharkhand": "జార్ఖండ్",
    "Karnataka": "కర్ణాటక", "Kerala": "కేరళ",
    "Madhya Pradesh": "మధ్యప్రదేశ్",
    "Maharashtra": "మహారాష్ట్ర",
    "Manipur": "మణిపూర్",
    "Meghalaya": "మేఘాలయ",
    "Mizoram": "మిజోరం",
    "Nagaland": "నాగాలాండ్",
    "Odisha": "ఒడిశా",
    "Punjab": "పంజాబ్", "Rajasthan": "రాజస్థాన్", "Sikkim": "సిక్కిం", "Tamil Nadu": "తమిళనాడు", "Telangana": "తెలంగాణ", "Tripura": "త్రిపుర",
    "Uttar Pradesh": "ఉత్తర ప్రదేశ్", "Uttarakhand": "ఉత్తరాఖండ్", "West Bengal": "పశ్చిమ బెంగాల్", "Andaman and Nicobar Islands": "అండమాన్ మరియు నికోబార్ దీవులు",
    "Chandigarh": "చండీగఢ్", "Dadra and Nagar Haveli": "దాద్రా మరియు నగర్ హవేలి", "Delhi": "ఢిల్లీ", "Lakshadweep": "లక్షద్వీప్", "Puducherry": "పుదుచ్చేరి"
    , "Jammu and Kashmir": "జమ్మూ కాశ్మీర్", "Ladakh": "లడఖ్", "Daman and Diu": "డామన్ మరియు డియు",
    // States Names End
    "You Chatted with these users using your name visible to them": "మీ పేరును ఉపయోగించి మీరు  వాడకందారుతో చాట్ చేసారు", "You Chatted with these users appearing as anonymous to them": "మీరు  అజ్ఞాతంగా ఈ  వాడకందారులతో చాట్ చేసారు",
    "Are you sure, you want to delete this post?": "మీరు ఖచ్చితంగా, మీరు ఈ పోస్ట్ను తొలగించాలనుకుంటున్నారా?", "day(s)": "రోజు(లు)", "package": "ప్యాకేజీ", "Km's": "కిలో మీటర్లు", "successfully": "సఫలం"
    , "Web Login": "వెబ్ లాగిన్", "Google": "గూగుల్", "Browser": "బ్రౌజర్", "Clear": "తొలగించు",
    "5) If Request is rejected, the user sending the request does not know it.This is a privacy Feature.": "5) అభ్యర్థన తిరస్కరించబడితే, అభ్యర్థనను పంపే వినియోగదారుకు అది తెలియదు. ఇది గోప్యతా ముఖ్య లక్షణం.",
    "7) You can edit anonymous to any name/nickname for ease of reference. The edited name / nickname will be only visible to you.": "7) మీ సౌలభ్యం కోసం మీరు అజ్ఞాతవ్యక్తి పేరును మరేదైనా  పేరు / మారుపేరుతో వరించవచ్చు. సవరించిన పేరు / మారుపేరు మీకు మాత్రమే కనిపిస్తుంది."
    , "SOS ! Help NEEDED !": "ఎస్‌ఓఎస్ (SOS) సహాయం అవసరం", "Connection Request Info": "కనెక్షన్ అభ్యర్థన సమాచారం", "A few moments ago": "కొన్ని క్షణాల క్రితం", "New Spaark Posting Details": "కొత్త స్పార్క్ పోస్టింగ్ వివరాలు",
    "Spaark Reported": "స్పార్క్ నివేదించింది"
    , "more time(s)": "మరిన్ని సార్లు", "Unmanaged traffic": "అనియంత్రిత రాకపోకలు", "Animal attack": "జంతు దాడి", "Eve-teasing": "స్త్రీలపై  వేధింపులు", "on the mobile app home screen.": "మొబైల్ యాప్ హోమ్ స్క్రీన్‌లో ",
    "Events &": "కార్యక్రమాలు-",
    "Feed": "సమాచారం",
    "Announcements": "ప్రకటనలు",
    "I Feel": "నాకు",
    "Emergency": "అత్యవసర",
    "Health": "ఆరోగ్య పరిస్థితి",
    "Lost &": "పోయినవి/",
    "Found": "దొరికినవి",
    "Community": "సమూహ",
    "Unsafe": "నాకు భయంగా ఉంది",
    "Find Anyone or": "ఎవరినైనా లేదా",
    "Services &": "వస్తువులు -",
    "Goods": "సేవలు",
    "Anything": "దేనినైనా కనుగొనండి",
    'Spaarks Connects you to users nearby': 'స్పార్క్స్ మిమ్మల్ని సమీపంలోని వాడకందారులతో అనుసంధానం చేస్తుంది',
    'A Spaark is Information posted by any user': 'స్పార్క్ అనేది వాడకందారులు పరిసరాల్లో ఉన్నవారికి పంపగల సమాచార ఖండిక (పోస్ట్‌)',
    'Users nearby can see this Spaark': 'పరిసర ప్రాంతాల్లోని వారెవరైనా మీ స్పార్క్ ను చూడవచ్చు',
    'Users can connect via Spaark': 'ఇతర వాడకందారులతో స్పార్క్ ద్వారా అనుసంధానం  కావచ్చు',
    'Spaark is freely visible upto a certain area/ radius': 'స్పార్క్ ఒక నిర్దిష్ట ప్రాంతం / వ్యాసార్థం వరకు ఉచితంగా కనిపిస్తుంది',
    'This Area/ Radius can be increased by the user': 'ఈ ప్రాంతం / వ్యాసార్థాన్ని వాడకందారు పెంచవచ్చు',
    'Slider to increase Area/ Radius': 'ప్రాంతం / వ్యాసార్థాన్ని వాడకందారు మార్చుకోవచ్చు',
    'Spaarks can advertise': 'స్పార్క్స్ ప్రకటనలు చూపించవచ్చు',
    'Spaarks can spread cheer and information': 'స్పార్క్స్ ఉల్లాసాలను మరియు సమాచారాన్ని వ్యాప్తి చేస్తాయి',
    'Spaarks can get Business': 'స్పార్క్స్ ద్వారా మీ వ్యాపారం అభివృద్ధిచెందవచ్చు',
    'Spaarks is new age social networking platform': 'స్పార్క్స్ ఒక కొత్త యుగం సోషల్ నెట్‌వర్కింగ్ వేదిక',
    'Spaark is freely visible upto a certain': 'స్పార్క్ ఒక నిర్దిష్ట ప్రాంతం / వ్యాసార్థం వరకు',
    'Area / Radius': 'ఉచితంగా కనిపిస్తుంది',
    "How": " ",
    "Upload MP4 Format Videos Only": "MP4 ఫార్మాట్ వీడియోలను మాత్రమే అప్‌లోడ్ చేయండి",
    "You cant upload more than one video": "మీరు ఒకటి కంటే ఎక్కువ వీడియోలను అప్‌లోడ్ చేయలేరు",
    "Password": "పాస్వర్డ్",
    "Confirm": "నిర్ధారించండి",
    "Incorrect Password": "పాస్వర్డ్ సరైనదికాదు",
    "Works": "ఎలా పనిచేస్తుంది",
    "How It Works": "ఎలా పనిచేస్తుంది",
    //new edited telugu
    "How Spaarks Works": "ఎలా పనిచేస్తుంది",
    "(Seller)": "విక్రేత",
    "Hindi": 'हिंदी',
    "List of Services": "సేవల జాబితా",
    "Active Packages Details": "క్రియాశీల ప్యాకేజీల వివరాలు",
    "Are you sure, you want to block this user?": "మీరు ఖచ్చితంగా, మీరు ఈ వ్యక్తిని నిరోధించాలనుకుంటున్నారా?",
    "Are you sure, you want to delete this Spaark?": "మీరు ఖచ్చితంగా, మీరు ఈ స్పార్క్ తొలగించాలనుకుంటున్నారా?", // Review once
    "Address(Optional)": "చిరునామా (ఐచ్ఛికం)",
    "Chats & Requests": "చాట్స్ అభ్యర్థనలు",
    "Click the application tour to know how Spaarks works.": "స్పార్క్స్ ఎలా పనిచేస్తుందో తెలుసుకోవడానికి అనువర్తన సందర్శను క్లిక్ చేయండి.",
    "Connection Request Sent": "కనెక్షన్ అభ్యర్థన పంపబడింది",
    "File size cannot exceed 5MB": "ఫైల్ పరిమాణం 5MB మించకూడదు",
    "Guide": "గైడ్",
    "Guide !": "గైడ్ !",
    "image size cannot exceed 25MB": "చిత్ర పరిమాణం 25MB మించకూడదు",
    "image size cannot exceed 5MB": "చిత్ర పరిమాణం 5MB మించకూడదు",
    "minimum length is 3": "కనిష్ట పొడవు 3",
    "Name can not be empty": "పేరు ఖాళీగా ఉండకూడదు",
    "No chats available": "చాట్‌లు ఏమి లేవు",
    "Personal Details": "వ్యక్తిగత సమాచారం",
    "Post Your Spaark": "మీ స్పార్క్ పోస్ట్ చేయండి",
    "Post your Spaark and get added in the list on the left side.": "మీ స్పార్క్‌ను పోస్ట్ చేయండి, ఎడమ వైపున ఉన్న జాబితాలో మీ స్పార్క్ కనిపిస్తుంది",
    "Posts": "పోస్ట్లు",
    "Search chats": "చాట్‌లను శోధించండి",
    "Select Connection option based on how you want others to connect with you.": "ఇతరులు మీతో ఎలా కనెక్ట్ కావాలని మీరు కోరుకుంటున్నారో దాని ఆధారంగా కనెక్షన్ ఎంపికను ఎంచుకోండి.",
    "Skip Tour": "టూర్ దాటవేయి",
    "Start Tour": "టూర్ ప్రారంభించండి",
    "These are glimpses of Spaarks around your location. Click on any to view full Spaark . It will navigate you into the respective feature": "ఇవి మీ ప్రాంతం చుట్టూగల స్పార్క్‌ల విహంగ వీక్షణం. వీటిలో దేనిమీదనైనా నొక్కడంద్వారా పూర్తి స్పార్క్ ను చూడండి. అది మిమ్మల్ని సంబంధిత విశేషతలోకి తీసుకెళ్తుంది.",
    "This ticket has been closed!": "ఈ టికెట్ మూసివేయబడింది!",
    "Upload an Image or a Video": "చిత్రం లేదా వీడియోను అప్‌లోడ్ చేయండి",
    "Upload Image Formats Only": "చిత్రలను మాత్రమే అప్‌లోడ్ చేయండి",
    "Video size cannot exceed 50MB": "వీడియో పరిమాణం 50MB మించకూడదు",
    "Welcome to Spaarks": "స్పార్క్స్‌కు స్వాగతం",
    "Your Spaark will be visible to the user in the radius covered as per your package.": "మీ ప్యాకేజీ ప్రకారం కవర్ చేయబడిన  పరిధిలో మీ స్పార్క్ వినియోగదారుకు కనిపిస్తుంది.",
    "Services listed in Spaarks": "స్పార్క్స్‌లో నమోదు చేయబడిన సేవలు",
    "Are you sure?": "ఖచ్చితంగా?",
    "Are you sure, you want to delete this Account?": "మీరు ఖచ్చితంగా,  ఖాతాను తొలగించాలనుకుంటున్నారా?",
    "For better experience of Spaarks, please use mobile application.": "మరింత మెరుగైన స్పార్క్స్ అనుభవం కోసం దయచేసి మొబైల్ యాప్‌ను వాడండి",
    "Services & Goods have these list of services": "సేవలు మరియు వస్తువుల వివరాలకోసం ఇక్కడ క్లిక్ చేయండి",
    "Add Nickname":"మారుపేరు జోడించండి",
    "Adds Fun. Helps you remember anonymous users.Only visible to you.":"వినోదాన్ని జోడిస్తుంది. అనామక వినియోగదారులను గుర్తుంచుకోవడానికి మీకు సహాయపడుతుంది. మీకు మాత్రమే కనిపిస్తుంది.",

    // //apptour breaks
    // 'SPAARKS app has': 'స్పార్క్స్  అనువర్తనంలో  మీరు',
    // 'features': ' ',
    // 'to be used by you': 'విశేషతలని ఉపయోగించుకోవచ్చు',
    // 'When you want to casually connect to a person in your vicinity keeping your privacy intact,': 'మీ సమీపంలోని వాడకందారుతో  మీ గోప్యతకు భంగంకలగకుండా సంధానం కావాలనుకున్నప్పుడు,',
    // 'is the feature for you.': 'విశేషత ఉపయోగపడుతుంది.',
    // 'feature is not just an ordinary feature. It is a way to inform around when you lose or find a lost person, a thing, or a pet.': 'విశేషత  సాధారణ విశేషత మాత్రమే కాదు. ఈ విశేషత ద్వారా మీరు  తప్పిపోయిన వ్యక్తిని, ఏదైనా  వస్తువును లేదా పెంపుడు జంతువును పోగొట్టుకున్న లేదా దొరికినప్పుడు  తెలియజేయడానికి ఇది ఒక గొప్ప వేదిక.',
    // 'use this feature to seek or to offer help, support, or queries related to health from people around you.': ', మీ చుట్టూ ఉన్న వ్యక్తుల నుండి ఆరోగ్యానికి సంబంధించిన సహాయం, మద్దతు లేదా అందించడానికి లేదా ఆరోగ్య పరమైన సందేహాల నివృత్తి కొరకు ఈ  విశేషతను  ఉపయోగించండి.',
    // 'feature is a great way to announce many things that you think to inform your locality. Be it your personal events or public announcements, use this feature for all good stuff.': ' फीचर आपके किसी भी आयोजन या कोई सार्वजनिक घोषणा को अपने आस पास के लोगो तक पहुंचाने का शानदार तरीका है।',
    // 'is a feature to offer or to seek help from people around you in case of unsafe feeling. Unsafe feeling may not always need a Police action.': ' फीचर में आप असुरक्षित स्तिथियों में अपने आस पास के लोगो को सूचित कर सकते हैं या उनकी मदद कर सकते हैं।',

    // 'is a place to connect with your community or locality for any sort of purpose.': ' फीचर में आप अपने आस पड़ोस के साथ अपनी प्रतिभा की तसवीरें, वीडिओज़, मेसेजेज़ आदि शेयर कर सकते हैं।',
    // 'is the most required feature for all those queries that can range from looking around for a foster parent for a stray puppy to reaching someone who can give you organic cabbages from their kitchen garden.': ' फीचर रोज़मर्रा की परिस्तिथियों में सबसे ज़रूरत की श्रेणी है। बहुत बार हम किसी काम के लिए किसी व्यक्ति या किसी चीज़ की खोज में होते हैं लेकिन यह समझ नहीं पाते की अपने आस पास उसे कैसे ढूंढे।  यह प्रश्न किसी भी प्रकार के हो सकते है। जैसे:- आवारा जानवर के लिए आश्रय की खोज, या किसी को अपने किचन गार्डन में उगी जैविक सब्ज़ियों के बारे में बताने के लिए। हमें नहीं पता होता की हमारे आस पास क्या क्या मिल सकता है।',
    // 'If you are looking for a Service or a Good to either buy or sell, you can easily become a buyer or seller in': 'यदि आप किसी सेवा या वस्तु को खरीदना या बेचना चाहते हैं तो आप ',
    // 'feature and connect to your clients or vendors who are around': 'फीचर का इस्तेमाल करें। आप इससे अपने आस पास के विक्रेताओं और ग्राहकों से संपर्क बना सकते हैं।',


    // 'SPAARK is available for a certain': 'स्पार्क एक निश्चित समय के लिए',
    // 'period. It can be ': 'उपलब्ध होता है। इसे मुफ्त में ',
    // 'reposted for free': 'रीपोस्ट किया जा सकता है।',
    // 'For increased ': 'ज़्यादा समय ',
    // 'Time ': 'और दूरी ',
    // 'and ': 'चुनने के ',
    // 'Distance': 'लिए स्लाइडर',
    // 'slider can be used to select': 'का इस्तेमाल कर सकते हैं।',

    // 'Click on Change': 'स्लाइडर पाने के लिए',
    // 'to get the slider': "'बदलें' बटन को दबाएं।",
    // 'Adjust the slider': 'समय और दूरी',
    // 'to increase Time': 'बढ़ाने के लिए स्लाइडर',
    // 'and Distance': 'एडजस्ट करें।',
    // 'Be on the move. Take Spaark along.':'जहाँ चलें स्पार्क साथ ले जाएँ।',
    // 'Post Spaark & move, access it elsewhere.':'स्पार्क पोस्ट करें, कहीं और से देखें',
    "Connections": "",
    "selectOneFromSix": "దయచేసి పై ఆరు ఎంపికలలో కనీసం ఒకదాన్ని ఎంచుకోండి.",
    "Are you sure you want to change the language?": "	మీరు భాషను మార్చాలనుకుంటున్నారా?",
    "You don't have new requests": "మీకు క్రొత్త అభ్యర్థనలు లేవు",
    "Format not supported": "ఫార్మటు సపోర్ట్ చేయబడదు",
    "File size cannot exceed 25MB": "ఫైల్ పరిమాణం 25MB మించకూడదు",
    "Seems like there are no spaarks around you, be the first one to post or move a bit further to find new spaarks": "మీ చుట్టూ స్పార్క్‌లు లేవని అనిపిస్తుంది, క్రొత్త స్పార్క్‌లను పోస్ట్ చేసిన మొదటి వ్యక్తి మీరే అవ్వవచ్చు లేదా కొంచెం ముందుకు వెళ్ళండి.",
    "No Spaarks Around You": "మీ చుట్టూ స్పార్క్స్ లేవు",
    "Write additional information here": "అదనపు సమాచారం ఇక్కడ వ్రాయండి",
    "Write about yourself and your service offerings here": "మీ గురించి మరియు మీ సేవాల గురించి ఇక్కడ వ్రాయండి.",
    "Copy": "నకలు చేయండి",
    "Exit": "ఎగ్జిట్",
    "Created At": "సృష్టించిన తేదీ",
    "submit": " సమర్పించండి",
    "Type your message here": "మీ సందేశాన్ని ఇక్కడ టైప్ చేయండి",
    "Spaark Reposted Successfully": "స్పార్క్ విజయవంతంగా రీపోస్ట్ చేయబడింది",
    "Please go to any feature to chat!": "చాట్ చేయడానికి దయచేసి ఏదైనా విశేషతలోనికి  వెళ్లండి",
    "Chat Cleared": "చాట్ క్లియర్ చేయబడింది",
    "Enter alias name": "అలియాస్ పేరును నమోదు చేయండి",
    "Be connected to your local area wherever you go!": "మీరు ఎక్కడికి వెళ్లినా మీ మీకు సమీపంలో ఉన్న ఇతర వాడకందారులతో కనెక్ట్ అవ్వండి",
    "Succesfully Updated": "విజయవంతంగా నవీకరించబడింది",
    "Request Accepted": "అభ్యర్థన అంగీకరించబడింది",
    // "Created at":""

    "Connecting as ": "గా కనెక్ట్ అవుతోంది ... ",
    "Home": "హోమ్",
    "Your Spaark has been reported.": "మీ స్పార్క్ నివేదించబడింది.",
    "Resell": "మారు విక్రయం",
    "Fashion": "ఫ్యాషన్",
    "Market": " మార్కెట్",
    "UNBLOCK": "నిషేధం తొలగించు",
    "Tutor": "బోధకులు",
    "Autorickshaw": "ఆటో రిక్షా",
    "Mechanic": "మెకానిక్",
    "Food": "ఆహారం",
    "Arts": "కళలు",
    "Beauty": "సౌందర్యం",
    "Fitness": "దృఢత్వం",
    "Real Estate": "స్థిరాస్తి",
    "Contact us": "మమ్మల్ని సంప్రదించండి",
    "Repair": "మరమ్మతు",
    "Profile": "ప్రొఫైల్",
    "Dietician": "ఆహార శాస్త్రవేత్త",
    "Stylist/Makeup": "స్టైలిస్ట్/మేకప్",
    "Ratings & Reviews": "రేటింగ్స్ & సమీక్షలు",
    "Ignore": "వదిలేయ్ ",
    "reviews": "సమీక్షలు",
    "Show more": "మరింత చూపు",
    "Show less": "తక్కువ చూపించు",
    "Removed Successfully": "విజయవంతంగా తొలగించబడింది",
    "Consultant": "సలహాదారు",
    "Freelancer": "స్వతంత్ర నిపుణుడు",
    "Lifestyle": "జీవనశైలి",
    "Store": "దుకాణం",
    "Worker": "కార్మికుడు",
    "All": "అన్ని",
    "Massage": "మాలీష్‌",
    "Event Planner": "కార్యక్రమ ప్రణాళిక కర్త",
    "Dhobi/Drycleaner": "రజక/డ్రై క్లీనర్",
    "Gardener": "తోటమాలి",
    "Yoga": "యోగా",
    "Tiffin": "టిఫిన్",
    "Tailor": "టైలర్",
    "Security Guard": "కాపలాదారి",
    "Dhaba": "ధాబా",
    "Home Based Food": "ఇంటి ఆహారం",
    "Panwala/Tea-stall": "పాన్/టీ దుకాణం",
    "Sweet Shop": "స్వీట్ల దుకాణాలు",
    "Content Writer": "సారాంశ రచయిత",
    "Toys": "బొమ్మలు",
    "Jeweller": "ఆభరణాలు",
    "Nursery": "మొక్కల పెంపకం",
    "Sent": "పంపబడింది",
    "Clear all": "అన్నితొలగించు",
    "Events": "కార్యక్రమాలు",
    "Continue": "కొనసాగించు",
    "Blocked users": "నిషేధిత వాడకందారులు",
    "Please Contact us": "దయచేసి మమ్మల్ని సంప్రదించండి",
    "Distance": "దూరం",
    "Time": "సమయం",
    "Login": "లాగిన్",
    "Request OTP": "OTP అభ్యర్థన",
    "Requests Sent": "అభ్యర్థన పంపబడింది",
    "Assistant": "సహాయకుడు",
    "Professional": "వృత్తి నిపుణులు",
    "Your comment has been reported.": "మీ వ్యాఖ్య నివేదించబడింది.",
    "Spaark anonymously": "అనామకంగా స్పార్క్ చేయండి",
    "Normal call": "ఫోన్ కాల్",
    "Spaarks call": "స్పార్క్స్ కాల్",
    "New friend request": "క్రొత్త స్నేహితుడి అభ్యర్థన",
    // "Lost & Found": "-పోగొట్టుకున్న/దొరికిన",
    "Health Emergency, Ask for Help, Lost or Found etc.": "పోగొట్టుకున్న/దొరికిన,అత్యవసర ఆరోగ్య పరిస్థితి,కోల్పోయింది లేదా కనుగొనబడింది",
    "Friend requests": "ఫ్రెండ్ రిక్వెస్ట్",
    "Friend Requests": "ఫ్రెండ్ రిక్వెస్ట్",
    "Bookmarks": "బుక్మార్క్స్ ",
    "Market profile": "మార్కెట్ ప్రొఫైల్",
    "Images posted": "పోస్ట్ చేసిన  ఇమేజ్ లు",
    "Make call from your personal number.": "మీ నెంబర్ తో కాల్ చేయండి",
    "Select any to create Spaark.":"స్పార్క్ సృష్టించడానికి ఏదైనా ఎంచుకోండి.",
    "ACCEPT FRIEND REQUEST": "అంగీకరించండి",
    "0 shares": "0 షేర్లు",
    "Shares": "షేర్లు",
    "shares": "షేర్లు",
    "Bookmarked successfully": " బుక్ మార్క్ చేయబడింది",
    "Requests received": "వచ్చిన రెక్యూస్ట్స్",
    "Received": "పొందింది",
    "No requests received": "అభ్యర్థనలు రాలేదు",
    "Oops, the spaark is deleted!": "స్పార్క్ తొలగించబడింది!",
    "within ": "లో",
    "beyond": "దాటి",
    "No Spaarks found with in": "లో స్పార్క్‌లు కనుగొనబడలేదు",
    "Spaarks chat": "స్పార్క్స్ చాట్",
    "Team Spaarks": "టీం స్పార్క్స్",
    "Your interests are saved successfully.": "మీ ఆసక్తులు విజయవంతంగా సేవ్ చేయబడ్డాయి.",
    "I am looking for any type of work.": "నేను ఏదైనా పని కోసం చూస్తున్నాను.",
    "IGNORE FRIEND REQUEST": "ఇగ్నోర్ ఫ్రెండ్ రిక్వెస్ట్",
    "Update photo": "ఫోటోను నవీకరించండి",
    "No profile for anonymous and makefriends": "అనామక మరియు మేక్‌ఫ్రెండ్‌ల కోసం ప్రొఫైల్ లేదు",
    "Maximum 3 numbers are allowed": "గరిష్టంగా 3 సంఖ్యలు అనుమతించబడతాయి",
    "Please login to bookmark profile": "బుక్‌మార్క్ చెయ్యడానికి దయచేసి  ప్రొఫైల్‌కు లాగిన్ అవ్వండి",
    "Please login to access this feature": "దయచేసి ఈ ఫీచర్‌ని యాక్సెస్ చేయడానికి లాగిన్ చేయండి",
    "Your session has been expired,Please login!": "మీ టైం సమాప్తం. మల్లి లాగిన్  అవ్వండి",
    "No images posted yet.": "చిత్రాలు ఇంకా పోస్ట్ చేయబడలేదు.",
    "Show my spaark on map":"మ్యాప్‌లో నా స్పార్క్ చూపించు",
    "Pulses/Grains": "పప్పుధాన్యాలు / ధాన్యాలు",
    "Poultry/Goat": "పౌల్ట్రీ/మేక",
    "Farm Machines": "వ్యవసాయ యంత్రాలు",
    "Farm Fresh":"తాజా వ్యవసాయ",
    "Offer a Service":"ఒక సేవను ఆఫర్ చేయండి",
    "Spaark remains at this location, even if you open the app at a new location":"మీరు క్రొత్త ప్రదేశంలో యాప్‌ని తెరిచినప్పటికీ, స్పార్క్ ఈ స్థానంలోనే ఉంటుంది",
    "Pin spaark at this location":"ఈ ప్రదేశంలో  స్పార్క్ ని పిన్ చేయండి",
    "Move spaark wherever I go":"నేను ఎక్కడికి వెళ్లినా స్పార్క్‌ను తరలించండి",
    "Dairy": "డైరీ",
    "Cow/Buffalo": "ఆవు/గేదె",
    "Please check your internet connection": "దయచేసి మీ ఇంటర్నెట్ కనెక్షన్‌ని తనిఖీ చేయండి",
    "Later": "తరువాత",
    "Services Offered": "సర్వీసెస్",
    "Sort": "క్రమబద్ధీకరించు",
    "views": "మంది చూసారు",
    "Announce": "అనౌన్స్",
    "Make Friends": "ఫ్రెండ్స్ చేస్కోండి",
    "Friends": "ఫ్రెండ్స్",
    "Make friends": "ఫ్రెండ్స్ చేస్కోండి",
    "User will not be able to chat or see each others Spaarks": "యూజర్స్  చాట్ చేయలేరు మరియు  ఒకరి స్పార్క్స్  మరొక్కరు  చూడలేరు",
    "More options": "మరిన్ని ఎంపికలు",
    "Connect with us": "మాతో కనెక్ట్ అవ్వండి",
    "Choose a service that suits you best": "మీకు బాగా సరిపోయే సేవను ఎంచుకోండి",
    "I give a Service": "నేను ఒక సర్వీస్ ఇస్తాను",
    "Terms and policies": "నిబంధనలు మరియు విధానాలు",
    "Spaarks timeline": "స్పార్క్స్ టైమ్‌లైన్",
    "Timeline": "టైమ్‌లైన్",
    "Quick Spaark": "శీఘ్ర స్పార్క్",
    "Have something to Sell": "అమ్మడానికి ఏదైనా కలిగి ఉంది",
    "I have Something to Sell": "నాకు అమ్మడానికి ఏదైనా కలిగి ఉంది",
    "Explore now": "ఎక్స్ప్లోర్ చేయండి",
    "Explore": "ఎక్స్ప్లోర్",
    "Spaarks are sorted by distance from you": "మీ నుండి దూరం ద్వారా స్పార్క్‌లు క్రమబద్ధీకరించబడతాయి",
    "Skip this Step": "ఈ దశను దాటవేయి",
    "Skip this step": "ఈ దశను దాటవేయి",
    "Add video": "వీడియోను జోడించండి",
    "Connection preferences": "కనెక్షన్ ప్రాధాన్యతలు",
    "Delete Friend Request": "ఫ్రెండ్ రిక్వెస్ట్ తొలగించు",
    "Allows other to make a regular call to you": "మీకు రెగ్యులర్ కాల్ చేయడానికి ఇతరులకి  అనుమతిస్తుంది",
    "Internet call where number is not required": "నంబర్ అవసరం లేని ఇంటర్నెట్ కాల్",
    "Show profile pic": "ప్రొఫైల్  పిక్  చూపించు",
    "Show my name": "నా పేరు చూపించు",
    "Simply post an anonymous spaark for other users around you to see by clicking here.": "ఇక్కడ క్లిక్ చేయడం ద్వారా మీ చుట్టూ ఉన్న ఇతర వినియోగదారుల కోసం అనామక స్పార్క్‌ను పోస్ట్ చేయండి.",
    "To start chat go to any spaark in make friends and click on request to chat.For anonymous chat turn off your name visibility while sending request to chat.": "చాట్ ప్రారంభించడానికి మేక్ ఫ్రెండ్స్ లోని ఏదైనా స్పార్క్ కి వెళ్లి, రిక్వెస్ట్ టు చాట్ పై క్లిక్ చేయండి. అనామక  చాట్ కోసం అభ్యర్థనను పంపేటప్పుడు మీ పేరు దృశ్యమానతను ఆపివేయండి.",
    "Job": "జాబ్",
    "Jobs": "జాబ్స్",
    "Want work": "పని కావాలి",
    "Want Work": "పని కావాలి",
    "Work":"పని",
    "Profiles": "ప్రొఫైల్స్",
    "No results found": "ఎటువంటి ఫలితాలు లభించలేదు",
    "Recent chats": "ఇటీవలి చాట్‌లు",
    "Hardware": "హార్డ్వేర్",
    "Telecom": "టెలికాం",
    "Furniture": "ఫర్నిచర్",
    "Construction": "నిర్మాణం",
    "Footwear": "పాదరక్షలు",
    "View all": "అన్ని చుడండి",
    "View less": "కొన్నే చుడండి",
    "Business enquires": "బిజినెస్ ఎన్క్యూరీస్",
    "Business enquiries": "బిజినెస్ ఎన్క్యూరీస్",
    "Update interests": "ఆసక్తులను అప్‌డేట్ చేయండి",
    "Donate": "దానం",
    "Resume chat": "చాట్ పునఃప్రారంభించండి",
    "To start a chat go to any spaark and click on chat.": "చాట్ ప్రారంభించడానికి ఏదైనా స్పార్క్‌కి వెళ్లి చాట్ మీద క్లిక్ చేయండి.",
    "Post a Spaark": "ఏదైనా స్పార్క్‌ను పోస్ట్ చేయండి",
    "Post Spaark": "పోస్ట్ స్పార్క్‌",
    "Announce Something": "ఏమైనా అనౌన్స్ చేయండి",
    "Post a Job": "జాబ్ పోస్ట్ చేయండి",
    "I have a skill.": "నాకు నైపుణ్యం ఉంది.",
    "or": "లేదా",
    "Or": "లేదా",
    "Remove photo": "ఫోటోను తొలగించండి",
    "Choose your language": "మీ భాషను ఎంచుకోండి",
    "Payment Related issues": "చెల్లింపు సంబంధిత సమస్యలు",
    "Payment Related issues?": "చెల్లింపు సంబంధిత సమస్యలు",
    "Previous tickets": "మునుపటి టిక్కెట్లు",
    "Seeds/Pesticides": "విత్తనాలు / పురుగుమందులు",
    "Skilled, Not Skilled, Part Time etc.": "నైపుణ్యం కలిగిన, నైపుణ్యం లేదు, పార్ట్ టైం",
    "Say Hello, Connect to a Stranger, Find a Date.": "హాలో చెప్పండీ,  అపరిచితుడికి కనెక్ట్ అవ్వండి",
    "Public Announcements, Events, Festivals, Launch, Party.": "బహిరంగ ప్రకటనలు, ఈవెంట్‌లు, పండుగలు, పార్టీ",
    "Labour, Assistant, Professional etc.": "కార్మిక, అస్సిస్టెంట్, వృత్తిపరమైన",
    "You don’t have any bookmarks yet": "మీకు ఇంకా బుక్మార్క్స్ ఏవీ లేవు",
    "Change language": "భాష మార్చు",
    "Phone number": "ఫోను నంబరు",
    "I Want a Job": "నాకు జాబ్ కావాలి",
    "I need a Service": "నాకు ఒక సేవ కావాలి",
    "Stylist, Electrician,Dhobi, Gardener, Repair etc.": "స్టైలిస్ట్, విద్యుత్‌, రజక, తోటమాలి, మరమ్మతు",
    "Maid, Driver, Plumber, Tuition, Freelancer etc.": "పనిమనిషి, డ్రైవర్, నీటిగొట్టాల పని నిపుణుడు, ట్యూషన్, స్వతంత్ర నిపుణుడు",
    "Fruits/Vegetables, Handicrafts, Homemade, Agri Mall etc.": "పండ్లు/కూరగాయలు, హస్తకళలు, ఇంటిలో తయారు, అగ్రి మాల్",
    "Agri Mall": "అగ్రి మాల్",
    "Education": "చదువు",
    "Medical Care": "వైద్య సంరక్షణ",
    "Stall": "స్టాల్",
    "Daily Services": "డైలి సర్వీసెస్",
    "Horoscope": "జాతకం",
    "Rent/Lease": "అద్దె/లీజు",
    "Travel/Transport": "ప్రయాణం/రవాణా",
    "Previous": "మునుపటి",
    "Next": "తరువాత",
    "Did not find your category?": "మీ విభాగాన్ని కనుగొనలేదా?",
    "choose at least one preference.": "కనీసం ఒక ప్రాధాన్యతను ఎంచుకోండి.",
    "Travel & Transport": "ప్రయాణం/రవాణా",
    "Choose your interests": "మీ ఆసక్తులను ఎంచుకోండి",
    "Select as many": "చాలా ఎంచుకోండి",
    "People": "ప్రజలు",
    "Local News": "స్థానిక సమాచారం",
    "Agri Malls": "అగ్రి మాల్స్",
    // "Find Date":""
    "Save & continue": "సేవ్ చెయ్యి & కొనసాగించు",
    "Services offered": "సర్వీసెస్",
    "Take": "మీ సేవ కోసం ఇక్కడ",
    "for your service here.": "తీసుకోండి",
    "Show QR": "QR చూపించు",
    "Write something about you.": "మీ గురించి ఏదైనా వ్రాయండి.",
    "Clinic": "క్లినిక్",
    "Gym": "వ్యాయామశాల",
    "Nurse/Caretaker": "నర్స్/సంరక్షకుడు",
    "Artist": "కళాకారుడు",
    "Music Band": "మ్యూజిక్ బ్యాండ్",
    "Coaching Centre": "కోచింగ్ సెంటర్",
    "Institute": "ఇనిస్టిట్యూట్",
    "Tuition": "ట్యూషన్",
    "Agents": "ఏజెంట్లు",
    "Financial Services": "ఆర్థిక సేవలు",
    "Beautician": "బ్యూటీషియన్",
    "Graphic Designer": "గ్రాఫిక్ డిజైనర్",
    "Software Developer": "సాఫ్ట్వేర్ డెవలపర్",
    "Medical Store": "మెడికల్ స్టోర్",
    "Doctor": "వైద్యుడు",
    "Did not find your field?": "మీ ఫీల్డ్ కనుగొనబడలేదా?",
    "Bag Repair": "బ్యాగ్ రిపేర్",
    // "Florist": "పూల వ్యాపారి",
    "Key Maker": "కీ మేకర్",
    "Kitchenware": "కిచెన్వేర్",
    "Scrap Collector": "స్క్రాప్ కలెక్టర్",
    "Shoe Repair": "షూ మరమ్మతు",
    "Electrician": "ఎలక్ట్రీషియన్",
    "Pest Control": "తెగులు నియంత్రణ",
    "Cafe/Parlour": "కేఫ్/పార్లర్",
    "Restaurant": "రెస్టారెంట్",
    "Salon": "సలోన్",
    "Write something": "ఏదైనా వ్రాయండి",
    "Landscape": "ప్రకృతి దృశ్యం",
    "Broadband/DTH": "బ్రాడ్‌బ్యాండ్/DTH",
    "Electricals": "ఎలక్ట్రికల్స్",
    "Electronics": "ఎలక్ట్రానిక్స్",
    "Printing": "ప్రింటింగ్",
    "Clothing": "దుస్తులు",
    "Automobiles": "ఆటోమొబైల్స్",
    "Books/Stationery": "పుస్తకాలు/స్టేషనరీ",
    "Cab/Taxi": "క్యాబ్/టాక్సీ",
    "Packers & Movers": "ప్యాకర్స్ & మూవర్స్",
    "Vehicle for Rent": "అద్దెకు వాహనం",
    "Dainik Majdoor": "దైనిక్ మజ్దూర్",
    "Choose an option": "ఒక ఎంపికను ఎంచుకోండి",
    "Add image": "చిత్రాన్ని జోడించండి",
    "Change location": "స్థానాన్ని మార్చండి",
    "Show directions": "దిశలను చూపు",
    "Comment here": "ఇక్కడ వ్యాఖ్యానించండి",
    "Please login to post a comment": "వ్యాఖ్యను పోస్ట్ చేయడానికి లాగిన్ చేయండి",
    "You have not blocked anyone yet.": "మీరు ఇంకా ఎవరినీ బ్లాక్ చేయలేదు.",
    "Yes": "అవును",
    "No": "లేదు",
    "By clicking “OK” you are agreeing to accept our cookie policies.": "సరే క్లిక్ చేయడం ద్వారా మీరు మా కుకీ పాలసీలను అంగీకరించడానికి అంగీకరిస్తున్నారు.",
    "Request to chat": "చాట్ చేయడానికి అభ్యర్థన",
    "No requests sent": "అభ్యర్థనలు పంపబడలేదు",
    "List of your spaarks for which you received requests.": "మీరు అభ్యర్థనలను స్వీకరించిన మీ స్పార్క్‌ల జాబితా.",
    "List of spaarks to which you sent requests": "మీరు అభ్యర్థనలు పంపిన స్పార్క్‌ల జాబితా",
    "Write the details you want to post here.": "మీరు పోస్ట్ చేయాలనుకుంటున్న వివరాలను ఇక్కడ వ్రాయండి.",
    "Add an image": "ఒక చిత్రాన్ని జోడించండి",
    "Connection permissons": "కనెక్షన్ అనుమతులు",
    "The way of connection you choose now, will always remain same with this user.": "మీరు ఇప్పుడు ఎంచుకున్న కనెక్షన్ మార్గం, ఈ వినియోగదారుతో ఎల్లప్పుడూ అలాగే ఉంటుంది.",
    "Send request": "అభ్యర్థన పంపు",
    "Click to send message": "సందేశం పంపడానికి క్లిక్ చేయండి",
    "You are anonymous to this user.": "మీరు ఈ యూజర్ కు అజ్ఞాతంగా ఉన్నారు.",
    // "Forward To":""
    "Type a message": "సందేశాన్ని టైప్ చేయండి",
    "User will not be able to chat or see each others spaarks.": "యూజర్ చాట్ చేయలేరు లేదా ఒకరికొకరు స్పార్క్స్ చూడలేరు.",
    "This clears entire chat with the user.": "ఇది వినియోగదారుతో మొత్తం చాట్‌ను క్లియర్ చేస్తుంది.",
    "This will not allow the other user to chat with you. You can still see each others spaarks.": "ఇది మీతో చాట్ చేయడానికి ఇతర వినియోగదారుని అనుమతించదు. మీరు ఇప్పటికీ ఒకరినొకరు స్పార్క్స్ చూడవచ్చు.",
    "Please drag the pin to your current location": "దయచేసి మీ ప్రస్తుత స్థానానికి పిన్‌ను లాగండి",
    "Choose City": "నగరాన్ని ఎంచుకోండి",
    "Share Spaark": "స్పార్క్‌ను షేర్ చేయండి",
    "It's your own Spaark.": "ఇది మీ స్వంత స్పార్క్.",
    "Are you sure, you want to report this Spaark?": "మీరు ఖచ్చితంగా, ఈ స్పార్క్‌ను నివేదించాలనుకుంటున్నారా?",
    "Bookmark removed": "బుక్‌మార్క్ తీసివేయబడింది",
    "What is the concept of this application?": "ఈ అప్లికేషన్ యొక్క భావన ఏమిటి?",
    "Connect to people in your local area.": "మీ స్థానిక ప్రాంతంలోని వ్యక్తులకు కనెక్ట్ అవ్వండి.",
    "What is a Spaark?": "స్పార్క్ అంటే ఏమిటి?",
    "A Spaark is the information posted by a user.": "ఒక స్పార్క్ అనేది వినియోగదారు పోస్ట్ చేసిన సమాచారం.",
    "What are the features in the application?": "అప్లికేషన్‌లోని ఫీచర్లు ఏమిటి?",
    "i.Announce  is about events, public announcements, ideas, thoughts, opinions, news, offers, celebrations, festivals, prayers etc in your local area. ii.Market is about promoting your Service, making customers in your local area. You can also share your Seller profile with others through Whatsapp. You can also connect with buyers of goods or services or find jobs or work around you.": "i.Anounounce అనేది మీ స్థానిక ప్రాంతంలో సంఘటనలు, బహిరంగ ప్రకటనలు, ఆలోచనలు, ఆలోచనలు, అభిప్రాయాలు, వార్తలు, ఆఫర్లు, వేడుకలు, పండుగలు, ప్రార్థనలు మొదలైన వాటి గురించి. ii.Market అనేది మీ సేవను ప్రోత్సహించడం, మీ స్థానిక ప్రాంతంలో కస్టమర్లను తయారు చేయడం. మీరు మీ విక్రేత ప్రొఫైల్‌ని Whatsapp ద్వారా ఇతరులతో పంచుకోవచ్చు. మీరు వస్తువులు లేదా సేవల కొనుగోలుదారులతో కూడా కనెక్ట్ కావచ్చు లేదా మీ చుట్టూ ఉద్యోగాలు లేదా పనిని కనుగొనవచ్చు.",
    "Why does the application take my location permissions?": "అప్లికేషన్ నా స్థాన అనుమతులను ఎందుకు తీసుకుంటుంది?",
    "Local area is defined by user’s actual location.": "స్థానిక ప్రాంతం వినియోగదారు వాస్తవ స్థానం ద్వారా నిర్వచించబడింది.",
    "What is the importance of radius shown on the map?": "మ్యాప్‌లో చూపిన వ్యాసార్థం యొక్క ప్రాముఖ్యత ఏమిటి?",
    "Radius gives the distance up to which you can see other Spaarks.": "వ్యాసార్థం మీరు ఇతర స్పార్క్‌లను చూడగలిగే దూరాన్ని ఇస్తుంది.",
    "Am I visible to others on the map when I log into the app?": "నేను యాప్‌లోకి లాగిన్ అయినప్పుడు మ్యాప్‌లో ఇతరులకు నేను కనిపిస్తున్నానా?",
    "No. Others can see your Spaark’s location if you allow it, but not your location.": "లేదు. మీరు అనుమతించినట్లయితే మీ స్పార్క్ స్థానాన్ని ఇతరులు చూడగలరు, కానీ మీ స్థానాన్ని చూడలేరు.",
    "Will other user's location be visible to me?": "ఇతర యూజర్ లొకేషన్ నాకు కనిపిస్తుందా?",
    "No.": "లేదు.",
    "What if I want my Spaark to be visible for more distance?": "నా స్పార్క్ ఎక్కువ దూరం కనిపించాలని నేను కోరుకుంటే?",
    "Leave a Business query with us.": "వ్యాపార ప్రశ్నను మాతో వదిలివేయండి.",
    "If I am a Seller, then how do I collect reviews for my service from buyers?": "నేను విక్రేత అయితే, కొనుగోలుదారుల నుండి నా సేవ కోసం నేను సమీక్షలను ఎలా సేకరించగలను?",
    "A Seller can collect a review from a user who got connected through Spaarks app. App will automatically direct both the users once a user connects a Seller.": "విక్రేత స్పార్క్స్ యాప్ ద్వారా కనెక్ట్ అయిన వినియోగదారు నుండి సమీక్షను సేకరించవచ్చు. ఒక వినియోగదారు విక్రేతను కనెక్ట్ చేసిన తర్వాత యాప్ స్వయంచాలకంగా ఇద్దరు వినియోగదారులను నిర్దేశిస్తుంది.",
    "How can I give review to a Seller?": "విక్రేతకు నేను ఎలా రివ్యూ ఇవ్వగలను?",
    "As a buyer if you have connected to a Seller, then the Seller will send you the request for giving review.": "కొనుగోలుదారుగా మీరు ఒక విక్రేతకు కనెక్ట్ అయి ఉంటే, అప్పుడు సమీక్షకుడు రివ్యూ కోసం అభ్యర్థనను మీకు పంపుతాడు.",
    "Can I edit my Spaark?": "నేను నా స్పార్క్‌ను సవరించవచ్చా?",
    "No. You cannot edit your Spaark after posting it. You can always delete it.": "లేదు. మీ స్పార్క్‌ను పోస్ట్ చేసిన తర్వాత మీరు దాన్ని సవరించలేరు. మీరు దీన్ని ఎల్లప్పుడూ తొలగించవచ్చు.",
    "How is a Spaark or a Content taken down?": "స్పార్క్ లేదా కంటెంట్ ఎలా తీసివేయబడింది?",
    "If Reports to a Spaark exceed a threshold level, it gets taken down automatically.": "స్పార్క్‌కు నివేదికలు ప్రవేశ స్థాయిని దాటితే, అది స్వయంచాలకంగా తీసివేయబడుతుంది.",
    "How does an account get suspended?": "ఖాతా ఎలా సస్పెండ్ అవుతుంది?",
    "An account whose Content is reported and taken down many times which exceeds the threshold level, the account gets suspended automatically.": "ఖాతా నివేదించబడిన మరియు ప్రవేశ స్థాయిని మించిన అనేక సార్లు తీసివేయబడిన ఖాతా, ఖాతా స్వయంచాలకంగా నిలిపివేయబడుతుంది.",
    "What is the maximum video size allowed to upload?": "అప్‌లోడ్ చేయడానికి అనుమతించబడిన గరిష్ట వీడియో పరిమాణం ఎంత?",
    "50 MB - 1 video.": "50 MB - 1 వీడియో.",
    "Will I be able to receive calls when I have logged out.": "నేను లాగ్ అవుట్ అయినప్పుడు కాల్స్ అందుకోగలనా.",
    "A user need to be logged into the app to receive the calls.": "కాల్స్ స్వీకరించడానికి ఒక యూజర్ యాప్‌లోకి లాగిన్ కావాలి.",
    "Can I recover a deleted chat?": "నేను తొలగించిన చాట్‌ను తిరిగి పొందవచ్చా?",
    "No. You cannot recover the chat, once deleted.": "లేదు. ఒకసారి తొలగించిన తర్వాత మీరు చాట్‌ను తిరిగి పొందలేరు.",
    "What happens when I exit a chat?": "నేను చాట్ నుండి నిష్క్రమించినప్పుడు ఏమి జరుగుతుంది?",
    "None of the users can exchange messages. You can resume the chat even after exiting.": "వినియోగదారులు ఎవరూ సందేశాలను మార్చుకోలేరు. నిష్క్రమించిన తర్వాత కూడా మీరు చాట్‌ను తిరిగి ప్రారంభించవచ్చు.",
    "What will be visible to the other user when I block him/her?": "నేను అతనిని/ఆమెను బ్లాక్ చేసినప్పుడు ఇతర యూజర్‌కు ఏమి కనిపిస్తుంది?",
    "Your details will remain confidential. Your Spaarks will not be shown to the blocked user. The blocked user can not chat with you any further.": "మీ వివరాలు గోప్యంగా ఉంటాయి. బ్లాక్ చేయబడిన వినియోగదారుకు మీ స్పార్క్స్ చూపబడవు. బ్లాక్ చేయబడిన యూజర్ ఇకపై మీతో చాట్ చేయలేరు.",
    "Couldn't find your query ?": "మీ ప్రశ్న దొరకలేదా?",
    "Previous conversations": "మునుపటి సంభాషణలు",
    "For any Promotions, Advertisements, Extended reach, etc.": "ఏదైనా ప్రమోషన్లు, ప్రకటనలు, విస్తరించిన రీచ్ మొదలైన వాటి కోసం.",
    "Type something": "ఏదైనా టైప్ చేయండి",
    "Type something to comment": "వ్యాఖ్యానించడానికి ఏదైనా టైప్ చేయండి",
    "Reply to Enquiry sent": "విచారణకు ప్రత్యుత్తరం పంపబడింది",
    "Blocked on": "బ్లాక్ చేయబడింది",
    "Unblocked successfully.": "విజయవంతంగా అన్‌బ్లాక్ చేయబడింది.",
    "Blocked successfully.":"",
    "No contacts in your forward list !": "మీ ఫార్వార్డ్ జాబితాలో పరిచయాలు లేవు!",
    "Only 4 files are allowed": "4 ఫైళ్లు మాత్రమే అనుమతించబడతాయి",
    "Only 3 images 1 video are allowed": "కేవలం 3 చిత్రాలు 1 వీడియో మాత్రమే అనుమతించబడతాయి",
    "Only 4 images are allowed": "4 చిత్రాలు మాత్రమే అనుమతించబడతాయి",
    "Text field cannot be empty": "టెక్స్ట్ ఫీల్డ్ ఖాళీగా ఉండకూడదు",
    "Only numbers are not allowed.": "సంఖ్యలు మాత్రమే అనుమతించబడవు.",
    "Please write something": "దయచేసి ఏదైనా వ్రాయండి",
    "Logged out Successfully": "విజయవంతంగా లాగ్ అవుట్ చేయబడింది",
    "please enter correct phone number": "దయచేసి సరైన ఫోన్ నంబర్ నమోదు చేయండి",
    "You have Entered Invalid Number": "మీరు చెల్లని సంఖ్యను నమోదు చేసారు",
    "You have Entered Wrong OTP": "మీరు తప్పు OTP ని నమోదు చేసారు",
    "invalid input": "చెల్లని ఇన్‌పుట్",
    "Minimum 3 characters are allowed": "కనీసం 3 అక్షరాలు అనుమతించబడతాయి",
    "Atleast 1 character should be there": "కనీసం 1 అక్షరం ఉండాలి",
    "Name should not contain Anonymous or anonymous": "పేరులో అజ్ఞాత లేదా అనామక ఉండకూడదు",
    "Please wait for user to accept your requests": "దయచేసి వినియోగదారు మీ అభ్యర్థనలను ఆమోదించే వరకు వేచి ఉండండి",
    "You have already requested this user, please go to requests and check": "మీరు ఇప్పటికే ఈ వినియోగదారుని అభ్యర్థించారు, దయచేసి అభ్యర్థనలకు వెళ్లి తనిఖీ చేయండి",
    " You are already connected, please go to chat and message": "మీరు ఇప్పటికే కనెక్ట్ అయ్యారు, దయచేసి చాట్ కి వెళ్ళండి మరియు మీ సందేశాన్ని వ్రాయండి",
    "You already have this user in your list": "మీరు ఇప్పటికే మీ జాబితాలో ఈ వినియోగదారుని కలిగి ఉన్నారు",
    "Your request is pending with the user.": "మీ అభ్యర్థన వినియోగదారు వద్ద పెండింగ్‌లో ఉంది.",
    "Please login to block": "దయచేసి బ్లాక్ చేయడానికి లాగిన్ చేయండి",
    "Spaark Deleted": "స్పార్క్ తొలగించబడింది",
    "Please login to bookmark post": "దయచేసి బుక్‌మార్క్ పోస్ట్‌కి లాగిన్ చేయండి",
    "Please login to like post": "దయచేసి పోస్ట్‌ను లైక్ చేయడానికి లాగిన్ చేయండి",
    "No profile for Anonymous and Makefriends": "అజ్ఞాత మరియు మేక్ ఫ్రెండ్స్ కోసం ప్రొఫైల్ లేదు",
    "Type something to send request": "అభ్యర్థనను పంపడానికి ఏదైనా టైప్ చేయండి",
    "Request has been sent successfully": "అభ్యర్థన విజయవంతంగా పంపబడింది",
    "Calls Available only on mobile Browsers": "మొబైల్ బ్రౌజర్లలో మాత్రమే కాల్స్ అందుబాటులో ఉంటాయి",
    "Name/Business Name. Should be less than 20 characters.": "పేరు/బిజినెస్ పేరు. 20 అక్షరాల కంటే తక్కువ ఉండాలి.",
    "Name/Business Name": "పేరు/బిజినెస్ పేరు",
    "Redirection Enabled for newly created tickets.": "కొత్తగా సృష్టించిన టిక్కెట్ల కోసం మళ్లింపు ప్రారంభించబడింది.",
    "Collect Review": "సమీక్షను సేకరించండి",
    "Did you complete your work with": "మీరు ఈ వ్యక్తితో మీ పనిని పూర్తి చేశారా-",
    "Not Yet": "ఇంకా లేదు",
    "Response recorded. Thank you.": "ప్రతిస్పందన నమోదు చేయబడింది. ధన్యవాదాలు",
    "Make a call": "కాల్ చేయుము",
    "MAKE A CALL": "కాల్ చేయుము",
    "Only available on mobile app": "మొబైల్ యాప్‌లో మాత్రమే అందుబాటులో ఉంటుంది",
    "Login to access this feature!": "ఈ ఫీచర్‌ను యాక్సెస్ చేయడానికి లాగిన్ చేయండి!",
    "Please fill valid mobile number": "దయచేసి చెల్లుబాటు అయ్యే మొబైల్ నంబర్‌ను పూరించండి",
    "Login using Mobile number": "మొబైల్ నంబర్ ఉపయోగించి లాగిన్ చేయండి",
    "You Canoot have more than two active sessions at a time. please logout of one session from your mobile app": "మీరు ఒకేసారి రెండు కంటే ఎక్కువ క్రియాశీల సెషన్‌లను కలిగి ఉండలేరు. దయచేసి మీ మొబైల్ యాప్ నుండి ఒక సెషన్ లాగ్ అవుట్ చేయండి",
    "Login to Spaarks": "స్పార్క్స్‌కు లాగిన్ అవ్వండి",
    "Login using QR": "QR తో లాగిన్ అవ్వండి",
    "Login using mobile": "మొబైల్‌తో లాగిన్ అవ్వండి",
    "Or Login using Mobile number": "లేదా మొబైల్ నంబర్ ఉపయోగించి లాగిన్ చేయండి",
    "By logging in you agree to our Terms & Policies.": "లాగిన్ చేయడం ద్వారా మీరు మా నిబంధనలు & విధానాలకు అంగీకరిస్తున్నారు",
    "Open Spaarks on your mobile phone.": "మీ మొబైల్ ఫోన్‌లో స్పార్క్‌లను తెరవండి.",
    "Click on QR icon.": "QR చిహ్నంపై క్లిక్ చేయండి.",
    "Scan this QR with you mobile phone.": "మీ మొబైల్ ఫోన్‌తో ఈ QR ని స్కాన్ చేయండి.",
    "You will recieve an": "మీరు మీ మొబైల్ నంబర్‌కు ",
    "on your mobile number.": "అందుకుంటారు",
    "Enter your Mobile Number": "మీ మొబైల్ నెంబర్ ను ఎంటర్ చేయండి",
    "We never share your mobile number with anyone": "మేము మీ మొబైల్ నంబర్‌ను ఎవరితోనూ పంచుకోము",
    "Enter": "నమోదు చేయండి",
    "OTP sent to": "OTP పంపబడింది",
    "Resend OTP": "OTP ను మళ్ళీ పంపు",
    "Wrong mobile number?": "తప్పు మొబైల్ నంబర్?",
    "One last step": "చివరి దశ",
    "You have no notifications yet.": "మీకు ఇంకా నోటిఫికేషన్‌లు లేవు.",
    "Chat request details": "చాట్ అభ్యర్థన వివరాలు",
    "DELETE FRIEND REQUEST": "ఫ్రెండ్ రిక్వెస్ట్ తొలగించు",
    "Based upon your response, we will approach the user to give you rating and review.": "మీ ప్రతిస్పందన ఆధారంగా, మీకు రేటింగ్ మరియు సమీక్ష ఇవ్వడానికి మేము వినియోగదారుని సంప్రదిస్తాము.",
    "Rate service provider/seller": "రేట్ సర్వీస్ ప్రొవైడర్/విక్రేత",
    "Write about your service experience": "మీ సేవా అనుభవం గురించి వ్రాయండి",
    "Owner of this Spaark disabled Spaarks call.":"ఈ స్పార్క్ యజమాని స్పార్క్స్ కాల్‌ను నిలిపివేసాడు.",
    "Owner of this Spaark disabled Normal call.":"ఈ స్పార్క్ యజమాని సాధారణ కాల్‌ను నిలిపివేసాడు.",
    "Owner of this Spaark disabled":"ఈ స్పార్క్ యజమాని",
    "option":"ఆప్షన్ నిలిపివేసాడు",
    "This option is available when you create a spaark":"మీరు ఒక స్పార్క్ సృష్టించినప్పుడు ఈ ఎంపిక అందుబాటులో ఉంటుంది",
    "No Spaarks found beyond":"దాటి స్పార్క్స్ కనుగొనబడలేదు",
    "Sort Spaarks by": "స్పార్క్‌లను క్రమబద్ధీకరించండి",
    "Spaarks are sorted by time of posting.": "పోస్ట్ చేసే సమయానికి స్పార్క్స్ క్రమబద్ధీకరించబడతాయి.",
    "Select City": "నగరాన్ని ఎంచుకోండి",
    "Show on googlemaps": "గూగుల్ మ్యాప్స్‌లో చూపించు",
    "Search Location": "స్థానాన్ని శోధించండి",
    "Popular Cities": "ప్రముఖ నగరాలు",
    "Market profile gets created when spaarks are posted in market category.": "మార్కెట్ వర్గంలో స్పార్క్‌లను పోస్ట్ చేసినప్పుడు మార్కెట్ ప్రొఫైల్ సృష్టించబడుతుంది.",
    "No services offered yet.": "ఇంకా సేవలు అందించబడలేదు.",
    "No spaarks created.":"స్పార్క్స్ సృష్టించబడలేదు.",
    "show less":"తక్కువ చూపించు",
    "Mumbai": "ముంబై",
    "Mumbai (or) Bombay": "ముంబై",
    "Bengaluru": "బెంగళూరు",
    "Bangalore (or) Bengaluru": "బెంగళూరు",
    "Hyderabad": "హైదరాబాద్",
    "Ahmedabad": "అహ్మదాబాద్",
    "Ahmadabad (or) Ahmedabad": "అహ్మదాబాద్",
    "Chennai": "చెన్నై",
    "Chennai (or) Madras": "చెన్నై",
    "Kolkata": "కోల్‌కతా",
    "Kolkata (or) Calcutta": "కోల్‌కతా",
    "Pune": "పూణే",
    "Sūrat": "సూరత్",
    "Lucknow": "లక్నో",
    "Jaipur": "జైపూర్",
    "Cawnpore(or) Kanpur": "కాన్పూర్",
    "Mirzāpur": "మీర్జాపూర్",
    "Mirzapur": "మీర్జాపూర్",
    "Nāgpur": "నాగ్‌పూర్",
    "Ghāziābād": "ఘజిబాద్",
    "Indore": "ఇండోర్",
    "Vadodara": "వడోదర",
    "Vishākhapatnam (or) Vizag": "విశాఖపట్నం",
    "Bhopāl": "భోపాల్",
    "Chinchvad (or) Chinchwad": "చించ్వాడ్",
    "Patna": "పాట్నా",
    "Ludhiāna": "లుధియానా",
    "Āgra": "ఆగ్రా",
    "Kalyān": "కళ్యాణ్",
    "Madurai": "మధురై",
    "Jamshedpur": "జంషెడ్‌పూర్",
    "Nāsik (or) Nashik": "నాసిక్",
    "Nasik (or) Nashik": "నాసిక్",
    "Nashik": "నాసిక్",
    "Farīdābād": "ఫరీదాబాద్",
    // "Aurangābād": "औरंगाबादी",
    "Rājkot": "రాజ్‌కోట్",
    "Meerut": "మీరట్",
    "Jabalpur": "జబల్పూర్",
    "Thāne": "థానే",
    "Dhanbād": "ధన్బాద్",
    "Allahābād": "అలహాబాద్",
    "Vārānasi": "వారణాసి",
    "Srīnagar": "శ్రీనగర్",
    "Amritsar": "అమృత్ సర్",
    "Alīgarh": "అలీఘర్",
    "Bhiwandi": "భివండీ",
    "Gwalior": "గ్వాలియర్",
    "Bhilai": "భిలాయ్",
    "Hāora": "హౌరా",
    "Rānchi": "రాంచీ",
    "Bezwāda": "బెజవాడ",
    "Chandīgarh": "చండీగఢ్",
    "Mysore": "మైసూర్",
    "Raipur": "రాయ్‌పూర్",
    "Kota": "కోటా",
    "Bareilly": "బరేలీ",
    "Jodhpur": "జోధ్‌పూర్",
    "Coimbatore": "కోయంబత్తూర్",
    "Dispur": "డిస్పూర్",
    "Guwāhāti": "గౌహతి",
    "Solāpur": "సోలాపూర్",
    "Trichinopoly": "ట్రిచినోపోలీ",
    "Hubli": "హుబ్లీ",
    "Jalandhar": "జలంధర్",
    "Bhubaneshwar (or) Bhubaneswar": "భువనేశ్వర్",
    "Bhayandar": "భాయందర్",
    "Morādābād": "మొరాదాబాద్",
    "Kolhāpur": "కోల్హాపూర్",
    "Thiruvananthapuram": "తిరువనంతపురం",
    "Sahāranpur": "సహారాన్పూర్",
    "Warangal": "వరంగల్",
    "Salem": "సేలం",
    "Mālegaon": "మాలెగావ్",
    "Kochi": "కొచ్చి",
    "Gorakhpur": "గోరఖ్‌పూర్",
    "Shimoga": "షిమోగా",
    "Tiruppūr": "తిరుప్పర్",
    "Guntūr": "గుంటూరు",
    "Raurkela": "రౌర్కెల",
    "Mangalore": "మంగళూరు",
    "Nānded": "నాందేడ్",
    "Cuttack": "కటక్",
    "Chānda (or) Chandrapur": "చంద్రాపూర్",
    "Dehra Dūn": "డెహ్రా డాన్",
    "Durgāpur": "దుర్గాపూర్",
    "Āsansol": "అసన్సోల్",
    "Bhāvnagar": "భావ్‌నగర్",
    "Amrāvati": "అమరావతి",
    "Amravati": "అమరావతి",
    "Nellore": "నెల్లూరు",
    "Ajmer": "అజ్మీర్",
    "Tinnevelly": "టిన్నెవెల్లి",
    "Bīkaner": "బికనీర్",
    "Agartala": "అగర్తలా",
    "Ujjain": "ఉజ్జయిని",
    "Jhānsi": "ఝాన్సీ",
    "Ulhāsnagar": "ఉల్లాస్ నగర్",
    "Davangere": "దావణగెరె",
    "Jammu": "జమ్మూ",
    "Belgaum": "బెల్గాం",
    "Gulbarga": "గుల్బర్గా",
    "Gulbarga (or) Kalaburagi": "గుల్బర్గా (మరియు) కల్బుర్గి",
    "Jāmnagar": "జామ్‌నగర్",
    "Dhūlia": "ధాలియా",
    "Gaya": "గయ",
    "Jalgaon": "జల్గావ్",
    "Kurnool": "కర్నూలు",
    "Udaipur": "ఉదయ్పూర్",
    "Bellary": "బళ్లారి",
    "Sāngli": "సాంగ్లీ",
    "Tuticorin": "ట్యూటికోరిన్",
    "Calicut": "కాలికట్",
    "Akola": "అకోలా",
    "Bhāgalpur": "భాగల్పూర్",
    "Sīkar": "సికార్",
    "Tumkūr": "తుమకూరు",
    "Quilon": "క్విలాన్",
    "Muzaffarnagar": "ముజఫర్‌నగర్",
    "Bhīlwāra": "భిల్వారా",
    "Nizāmābād": "నిజామాబాద్",
    "Bhātpāra": "భట్పారా",
    "Kākināda": "కాకినాడ",
    "Parbhani": "పరభాణి",
    "Pānihāti": "పాణిహతి",
    "Lātūr": "లాతూర్",
    "Rohtak": "రోహ్తక్",
    "Rājapālaiyam": "రాజపాలయం",
    "Ahmadnagar": "అహ్మద్ నగర్",
    "Cuddapah": "కడప",
    "Kadapa": "కడప",
    "Rājahmundry": "రాజమండ్రి",
    "Alwar": "ఆళ్వార్",
    "Muzaffarpur": "ముజఫర్‌పూర్",
    "Bilāspur": "బిలాస్‌పూర్",
    "Mathura": "మధుర",
    "Kāmārhāti": "కమరహతి",
    "Saugor": "సౌగర్",
    "Bijāpur (or) Vijayapura": "బిజాపూర్ (లేదా) విజయపుర",
    "Brahmapur (or) Berhampur": "బ్రహ్మపూర్ (లేదా) బెర్హంపూర్",
    "Shāhjānpur": "షాజహాన్పూర్",
    "Trichūr  (or) Thrissur": "త్రిచూర్ (లేదా) త్రిసూర్",
    "Barddhamān": "బర్ధమాన్",
    "Sambalpur": "సంబల్పూర్",
    "Purnea": "పుర్నియా",
    "Hisar": "హిసార్",
    "Fīrozābād": "ఫిరోజాబాద్",
    "Bīdar": "బీదర్",
    "Rāmpur": "రాంపూర్",
    "Shiliguri": "సిలిగురి",
    "Bāli": "బాలి",
    "Pānīpat": "పానిపట్",
    "Karīmnagar": "కరీంనగర్",
    "Bhuj": "భుజ్",
    "Ichalkaranji": "ఇచల్‌కరాంజీ",
    "Tirupati": "తిరుపతి",
    "Hospet": "కొత్తపేట",
    "Āīzawl": "ఐజ్వాల్",
    "Sannai": "సన్నాయి",
    "Bārāsat": "బరాసత్",
    "Ratlām": "రత్లం",
    "Handwāra": "హంద్వారా",
    "Drug": "దుర్గ్",
    "Imphāl": "ఇంఫాల్",
    "Anantapur (or) Anantapuram": "అనంతపురం (లేదా) అనంతపురం",
    "Etāwah": "ఎటావా",
    "Rāichūr": "రాయచూర్",
    "Ongole": "ఒంగోలు",
    "Bharatpur": "భరత్పూర్",
    "Begusarai": "బెగుసరాయ్",
    "Sonīpat": "సోనిపట్",
    "Rāmgundam": "రామగుండం",
    "Hāpur": "హాపూర్",
    "Uluberiya": "ఉలుబెరియా",
    "Porbandar": "పోర్బందర్",
    "Pāli": "పాలి",
    "Vizianagaram": "విజయనగరం",
    "Puducherry(or) Pondicherry": "పుదుచ్చేరి (లేదా) పాండిచ్చేరి",
    "Karnāl": "కర్నాల్",
    "Nāgercoil": "నాగర్‌కోయిల్",
    "Tanjore": "తంజోర్",
    "Sambhal": "సంభాల్",
    "Shimla": "సిమ్లా",
    "Ghāndīnagar": "గాంధీనగర్",
    "Shillong": "షిల్లాంగ్",
    "New Delhi": "న్యూఢిల్లీ",
    "Port Blair": "పోర్ట్ బ్లెయిర్",
    "Gangtok": "గ్యాంగ్‌టాక్",
    "Kohīma": "కోహిమా",
    "Itānagar": "ఇటానగర్",
    "Panaji": "పనాజీ",
    "Damān": "డామన్",
    "Kavaratti": "కవరట్టి",
    "Panchkula": "పంచకుల",
    "Kagaznāgār": "కాగజ్ నగర్",
    "Adoni": "ఆదోని",
    "Alappuzha": "అలప్పుజా",
    "Ambala": "అంబాలా",
    "Ambattur": "అంబత్తూరు",
    "Amroha": "అమ్రోహా",
    "Anand": "ఆనంద్",
    "Arrah": "అర్రా",
    "Avadi": "అవడి",
    "Bahraich": "బహరైచ్",
    "Ballia": "బల్లియా",
    "Bally": "బల్లి",
    "Baranagar or Baranagore": "బరానగర్ లేదా బరనాగోర్",
    "Bathinda": "బటిండా",
    "Bettiah": "బెట్టియా",
    "Bhalswa Jahangir Pur": "భల్స్వా జహంగీర్ పుర్",
    "Bhimavaram": "భీమవరం",
    "Bhind": "భింద్",
    "Bhiwani": "భివానీ",
    "Bhusawal": "భూసవాల్",
    "Bidhannagar": "బిధానగర్",
    "Bihar Sharif": "బీహార్ షరీఫ్",
    "Bokaro": "బొకారో",
    "Bongaigaon": "బొంగాగావ్",
    "Bulandshahr": "బులంద్‌షహర్",
    "Burhanpur": "బుర్హాన్పూర్",
    "Buxar": "బక్సర్",
    "Chapra": "చప్రా",
    "Chittoor": "చిత్తూరు",
    "Danapur": "దానాపూర్",
    "Darbhanga": "దర్భాంగా",
    "Dehri": "డెహ్రీ",
    "Deoghar": "देదేవఘర్वघर",
    "Dewas": "దేవాస్",
    "Dharmavaram": "ధర్మవరం",
    "Dhule": "ధూలే",
    "Dibrugarh": "దిబ్రుగర్",
    "Dindigul": "దిండిగల్",
    "Erode": "ఈరోడ్",
    "Farrukhabad": "ఫరూఖాబాద్",
    "Fatehpur": "ఫతేపూర్",
    "Gandhidham": "గాంధీధం",
    // "Giridih": "गिरिडीह",
    "Gopalpur": "గోపాల్పూర్",
    "Gudivada": "గుడివాడ",
    "Guna": "గుణ",
    "Guntakal": "గుంతకల్",
    "Hajipur": "హాజీపూర్",
    "Haridwar": "హరిద్వార్",
    "Hazaribagh": "హజారీబాగ్",
    "Hindupur": "హిందూపూర్",
    "Hosur": "హోసూర్",
    "Howrah": "హౌరా",
    "Hubli–Dharwad": "హుబ్లి – ధార్వాడ్",
    "Jalna": "జల్నా",
    "Jamalpur": "జమాల్పూర్",
    "Jaunpur": "జౌన్పూర్",
    "Jehanabad": "జెహనాబాద్",
    "Jorhat": "జోర్హాట్",
    "Ludhiana": "లుధియానా",
    "Surat": "సూరత్",
    "Junagadh": "జునాగఢ్",
    "Kalyan-Dombivli": "కళ్యాణ్-దోంబివ్లి",
    "Kalyan": "కళ్యాణ్",
    "Karaikudi": "కారైకుడి",
    "Karawal Nagar": "కరవాల్ నగర్",
    "Nagpur": "నాగపూర్",
    "Varanasi": "వారణాసి",
    "Katihar": "కటిహార్",
    "Katni": "కట్నీ",
    "Kavali": "కావలి",
    "Khandwa": "ఖాండ్వా",
    "Kharagpur": "ఖరగ్‌పూర్",
    "Khora-Ghaziabad\"": "ఖోరా-ఘజియాబాద్",
    "Ghaziabad": "ఘజియాబాద్",
    "Thane": "థానే",
    "Bhopal": "భోపాల్",
    "Kirari Suleman Nagar": "కిరారి సులేమాన్ నగర్",
    "Kishanganj": "కిషన్‌గంజ్",
    "Kollam": "కొల్లం",
    "Kottayam": "కొట్టాయం",
    "Kozhikode": "కోజీకోడ్",
    "Kumbakonam": "కుంభకోణం",
    "Loni": "లోని",
    "Machilipatnam": "మచిలీపట్నం",
    "Madanapalle": "మదనపల్లె",
    "Madhyamgram": "మధ్యగ్రామ్",
    "Mahbubnagar": "మహబూబ్‌నగర్",
    "Maheshtala": "మహేశతల",
    "Malda": "మాల్డా",
    // "Mango": "",
    "Mau": "మౌ",
    "Medininagar": "మేదినగర్",
    "Daltonganj": "డాల్టోంగాంజ్",
    "Mehsana": "మెహసానా",
    "Mira-Bhayandar": "మీరా-భయందర్",
    "Miryalaguda": "మిర్యాలగూడ",
    "Morbi": "మోర్బి",
    "Morena": "మొరెనా",
    "Motihari": "మోతిహరి",
    "Munger": "ముంగర్",
    "Nadiad": "నాడియాడ్",
    "Nagaon": "నాగావ్",
    "Naihati": "నైహతి",
    "Nandyal": "నంద్యాల",
    "Nangloi Jat": "నాంగ్లోయ్ జాట్",
    "Narasaraopet": "నరసరావుపేట",
    "Noida": "నోయిడా",
    "North Dumdum": "ఉత్తర డమ్‌డమ్",
    "Orai": "ఒరై",
    "Pallavaram": "పల్లవరం",
    "Panvel": "పన్వేల్",
    "Phagwara": "ఫగ్వారా",
    "Phusro": "ఫుస్రో",
    "Pimpri-Chinchwad": "పింప్రి-చించ్వాడ్",
    "Proddatur": "ప్రొద్దుటూరు",
    "Pudukkottai": "పుదుక్కోట్టై",
    "Purnia": "పూర్ణియా",
    "Raebareli": "రాయబరేలి",
    "Raiganj": "రాయగంజ్",
    // // "Raipur":""
    "Rajpur Sonarpur": "రాజ్‌పూర్ సోనార్‌పూర్",
    "Ramgarh": "రామ్‌గఢ్",
    "Raurkela Industrial Township": "రూర్కెలా ఇండస్ట్రియల్ టౌన్‌షిప్",
    "Rewa": "రేవా",
    "Sagar": "సాగర్",
    "Saharsa": "సహర్సా",
    "Satara": "సతారా",
    "Satna": "సాత్నా",
    "Secunderabad": "సికింద్రాబాద్",
    "Serampore": "సెరంపోర్",
    "Shivpuri": "శివపురి",
    "Silchar": "సిల్చార్",
    "Singrauli": "సింగ్రౌలి",
    "Sirsa": "సిర్సా",
    "Siwan": "సివాన్",
    "South Dumdum": "దక్షిణ డమ్‌డమ్",
    "Sri Ganganagar": "శ్రీ గంగానగర్",
    "Srikakulam": "శ్రీకాకుళం",
    "SultanPur Majra": "సుల్తాన్ పూర్ మజ్రా",
    "Surendranagar Dudhrej": "సురేంద్రనగర్ దుధ్రేజ్",
    "Suryapet": "సూర్యాపేట",
    "Tadepalligudem": "తాడేపల్లిగూడెం",
    "Tadipatri": "తాడిపత్రి",
    "Tenali": "తెనాలి",
    "Tezpur": "తేజ్‌పూర్",
    "Thanjavur": "తంజావూరు",
    "Thoothukudi": "తూత్తుకుడి",
    "Tinsukia": "తిన్సుకియా",
    // "Aurangabad": "औरंगाबाद",
    "Amaravati": "అమరావతి",
    "Yamunanagar": "యమునానగర్",
    "Vijayawada (or) Bezawada": "విజయవాడ (లేదా) బెజవాడ",
    "Tiruvannamalai": "తిరువణ్ణామలై",
    "Tirur": "తిరూర్",
    "Berhampore (or) Baharampur or Berhampur": "బెర్హంపూర్ (లేదా) బహరంపూర్ లేదా బెర్హంపూర్",
    "Chinsurah (or) Chuchura": "చిన్సురా (లేదా) చుచురా",
    "Eluru (or) Ellore": "ఏలూరు (లేదా) ఎల్లూరు",
    "Gurgaon (or) Gurugram": "గుర్గావ్ (లేదా) గురుగ్రామ్",
    "Khammam (or) Khammamett": "ఖమ్మం (లేదా) ఖమ్మమెట్టు",
    "Navi Mumbai (or) New Bombay": "నవీ ముంబై (లేదా) కొత్త బొంబాయి",
    "Sasaram (or) Sahasram": "ససారం (లేదా) సహస్రం",
    "Tiruchirappalli (or) Tiruchi (or) Trichy": "తిరుచిరాపల్లి (లేదా) తిరుచ్చి (లేదా) తిరుచ్చి",
    "Bokaro Steel City": "బొకారో స్టీల్ సిటీ",
    
    "Hamirpur": "హమీర్‌పూర్",
    "Haora": "హౌరా",
    "Kannur": "కన్నూర్",
    "Malappuram": "మలప్పురం",
    "Palakkad": "పాలక్కాడ్",
    "Perinthalmanna": "పెరింతల్మన్నా",
    "Purulia": "పురులియా",
    "Tirunelveli": "తిరునల్వేలి",
    "Tiruvottiyur": "తిరువొత్తియూర్",
    "Udupi": "ఉడిపి",
    "Unnao": "ఉన్నావ్",
    "Uzhavarkarai": "ఉజవర్కరై",
    "Marie Oulgaret": "మేరీ ఓల్గారెట్",
    "Vasai-Virar": "వసాయ్-విరార్",
    "Vasco Da Gama": "వాస్కోడాగామా",
    "Vellore": "వేలూరు",
    "Patiala": "పాటియాలా",
    "Kulti": "కుల్తి",
    "Allahabad": "అలహాబాద్",
    "Moradabad": "మొరాదాబాద్",
    "Patiāla":"పాటియాలా",
    "error encountered":"లోపం ఎదురైంది",
    "User can give you rating by scanning this QR code.":"ఈ QR కోడ్‌ని స్కాన్ చేయడం ద్వారా యూజర్ మీకు రేటింగ్ ఇవ్వవచ్చు.",
    "You Cannot have more than two active sessions at a time. please logout of one session from your mobile app ":"మీరు ఒకేసారి రెండు కంటే ఎక్కువ క్రియాశీల సెషన్‌లను కలిగి ఉండలేరు. దయచేసి మీ మొబైల్ యాప్ నుండి ఒక సెషన్ లాగ్ అవుట్ చేయండి",
    "Looking for something":"వెతకండి",
    "Search in":"శోధించండి",
    "Need":"అవసరం",
  "You have a notification":"మీకు నోటిఫికేషన్ ఉంది",
  "New Notification":"కొత్త నోటిఫికేషన్",
  "Someone has commented on your post.":"మీ పోస్ట్‌పై ఎవరో వ్యాఖ్యానించారు.",
  "click to view":"చూడటానికి క్లిక్ చేయండి",
  "Bookmark removed successfully":"బుక్ మార్క్ తొలగించబడింది",
  "Note : You can also disable Spaarks call while posting a Spaark":"గమనిక: స్పార్క్‌ను పోస్ట్ చేసేటప్పుడు మీరు స్పార్క్స్ కాల్‌ను కూడా డిసేబుల్ చేయవచ్చు",
  "Close":"మూసివేయండి",
  "New spaark":"న్యూ స్పార్క్",
  "Bezwada":"బెజవాడ",
  "Bhavnagar":"భావనగర్",
  "Bikaner":"బికనీర్",
  "Nizamabad":"నిజామాబాద్",
  "Bhagalpur":"భాగల్పూర్",
  "Bhilwara":"భిల్వారా",
  "Bilaspur":"బిలాస్‌పూర్",
  "Chanda (or) Chandrapur":"చందా (లేదా) చంద్రపూర్",
  "Nagercoil":"నాగర్‌కోయిల్",
  "Trichur  (or) Thrissur":"త్రిచూర్ (లేదా) త్రిసూర్",
  "Ranchi":"రాంచీ",
  "Raichur":"రాయచూర్",
  "Nanded":"నాందేడ్",
  "Dehra Dun":"డెహ్రా డన్",
  "Malegaon":"మాలెగావ్",
  "Firozabad":"ఫిరోజాబాద్",
  "Faridabad":"ఫరీదాబాద్",
  "Ulhasnagar":"ఉల్లాస్ నగర్",
  "Jamnagar":"జామ్‌నగర్",
  "Srinagar":"శ్రీనగర్",
  "Guntur":"గుంటూరు",
  "Sangli":"సాంగ్లీ",
  "Vishakhapatnam (or) Vizag":"విశాఖపట్నం (లేదా) వైజాగ్",
  "Agra":"ఆగ్రా",
  "Tiruppur":"తిరుప్పూర్",
  "Rajkot":"రాజ్‌కోట్",
  "Rajahmundry": "రాజమండ్రి",
  "Shahjanpur": "షాజహాన్పూర్",
  "Bijapur (or) Vijayapura": "బీజాపూర్ (లేదా) విజయపుర",
  "Jhansi": "ఝాన్సీ",
    // // "Patiāla": "पटियाला",
    // "Mango": "मानगो",
    "Rajapalaiyam":"రాజపాలయం",
    "Kolhapur":"కొల్హాపూర్",
    "Sikar":"సికార్",
    "Kamarhati":"కమరహతి",
    "Tumkur":"తుమకూరు",
    "Kagaznagar":"కాగజ్ నగర్",
    "Karimnagar":"కరీంనగర్",
    "Solapur":"షోలాపూర్",
    "Asansol":"అసన్సోల్",
    "Panihati":"పనిహతి",
    "Barasat":"బరాసత్",
    "Latur":"లాతూర్",
    "Bhatpara":"భట్పారా",
    "Aizawl":"ఐజ్వాల్",
    "Etawah":"ఎటావా",
    "Guwahati":"గౌహతి",
    "Handwara":"హంద్వారా",
    "Web login":"వెబ్ లాగిన్",
  }

}
